#!/usr/bin/env python3
"""Build crawler-readable publication pages, a sitemap, and an IndexNow manifest."""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PUBLICATIONS_FILE = ROOT / "_data" / "publications.json"
PUBLICATIONS_DIR = ROOT / "publications"
SITEMAP_FILE = ROOT / "sitemap.xml"
INDEXNOW_FILE = ROOT / "indexnow.json"

BASE_URL = "https://ramtin-mojtahedi.github.io"
PERSON_ID = f"{BASE_URL}/#person"
ORCID_URL = "https://orcid.org/0000-0002-3953-3256"
INDEXNOW_KEY = "898f0caec5d8b22a095db2a4afa88722"
INDEXNOW_KEY_FILE = ROOT / f"{INDEXNOW_KEY}.txt"
GENERATED_MARKER = "<!-- Generated by scripts/build_search_pages.py; do not edit. -->"


def esc(value: object, *, attribute: bool = False) -> str:
    return html.escape(str(value or ""), quote=attribute)


def plain_text(value: object) -> str:
    text = str(value or "")
    text = re.sub(r"<sup\b[^>]*>.*?</sup>", "", text, flags=re.IGNORECASE | re.DOTALL)
    text = re.sub(r"<[^>]+>", "", text)
    return re.sub(r"\s+", " ", html.unescape(text)).strip()


def author_names(publication: dict[str, object]) -> list[str]:
    names = publication.get("authors")
    if isinstance(names, list) and all(isinstance(name, str) and name.strip() for name in names):
        return [name.strip() for name in names]
    text = plain_text(publication.get("authors_html", "")).rstrip(".")
    text = re.sub(r",?\s+and\s+", ", ", text, flags=re.IGNORECASE)
    return [part.strip().rstrip(".") for part in text.split(",") if part.strip()]


def citation_author_names(publication: dict[str, object]) -> list[str]:
    names = publication.get("citation_authors")
    if isinstance(names, list) and all(isinstance(name, str) and name.strip() for name in names):
        return [name.strip() for name in names]
    return author_names(publication)


def is_ramtin(name: str) -> bool:
    normalized = re.sub(r"[^a-z]", "", name.lower())
    return "mojtahedi" in normalized or normalized in {
        "rmsaffari",
        "ramtinmojtahedisaffari",
    }


def author_schema(name: str) -> dict[str, object]:
    if is_ramtin(name):
        return {
            "@type": "Person",
            "@id": PERSON_ID,
            "name": name,
            "alternateName": ["Ramtin Mojtahedi", "Ramtin Mojtahedi Saffari", "R. M. Saffari"],
            "sameAs": ORCID_URL,
        }
    return {"@type": "Person", "name": name}


def description_for(title: str, *, has_doi: bool) -> str:
    detail = "authors, venue, year, and DOI" if has_doi else "authors, venue, and year"
    suffix = f" Publication record for Dr. Ramtin Mojtahedi with {detail}."
    available = 155 - len(suffix)
    short_title = title if len(title) <= available else title[: max(0, available - 1)].rstrip() + "…"
    return short_title + suffix


def publication_url(publication: dict[str, object]) -> str:
    return f"{BASE_URL}/publications/{publication['id']}/"


def json_script(payload: object) -> str:
    serialized = json.dumps(payload, ensure_ascii=False, indent=2).replace("</", "<\\/")
    return f'<script type="application/ld+json">\n{serialized}\n  </script>'


def scholar_date(value: object) -> str:
    date = str(value or "")
    return date.replace("-", "/") if re.fullmatch(r"\d{4}-\d{2}-\d{2}", date) else date


def citation_container(publication: dict[str, object]) -> dict[str, object] | None:
    venue = str(publication.get("venue") or "").strip()
    volume = str(publication.get("volume") or "").strip()
    publication_type = str(publication.get("type") or "")
    if not venue:
        return None
    if publication_type == "journal-article":
        periodical: dict[str, object] = {"@type": "Periodical", "name": venue}
        if volume:
            return {
                "@type": "PublicationVolume",
                "volumeNumber": volume,
                "isPartOf": periodical,
            }
        return periodical
    if volume:
        return {
            "@type": "PublicationVolume",
            "volumeNumber": volume,
            "isPartOf": {"@type": "CreativeWork", "name": venue},
        }
    return {"@type": "CreativeWork", "name": venue}


def citation_meta(publication: dict[str, object]) -> str:
    publication_type = str(publication.get("type") or "")
    venue = str(publication.get("venue") or "").strip()
    volume = str(publication.get("volume") or "").strip()
    issue = str(publication.get("issue") or "").strip()
    pages = str(publication.get("pages") or "").strip()
    article_number = str(publication.get("article_number") or "").strip()
    doi = str(publication.get("doi") or "").strip()
    lines = [
        f'  <meta name="citation_author" content="{esc(name, attribute=True)}">'
        for name in citation_author_names(publication)
    ]
    if venue:
        field = "citation_journal_title" if publication_type == "journal-article" else "citation_conference_title"
        lines.append(f'  <meta name="{field}" content="{esc(venue, attribute=True)}">')
    if volume:
        lines.append(f'  <meta name="citation_volume" content="{esc(volume, attribute=True)}">')
    if issue:
        lines.append(f'  <meta name="citation_issue" content="{esc(issue, attribute=True)}">')
    if pages:
        page_parts = re.split(r"\s*[-–—]\s*", pages, maxsplit=1)
        lines.append(f'  <meta name="citation_firstpage" content="{esc(page_parts[0], attribute=True)}">')
        if len(page_parts) == 2:
            lines.append(f'  <meta name="citation_lastpage" content="{esc(page_parts[1], attribute=True)}">')
    elif article_number:
        lines.append(f'  <meta name="citation_firstpage" content="{esc(article_number, attribute=True)}">')
    if doi:
        lines.append(f'  <meta name="citation_doi" content="{esc(doi, attribute=True)}">')
    return "\n".join(lines)


def publication_page(publication: dict[str, object]) -> str:
    title = str(publication["title"])
    year = int(publication["year"])
    publication_date = str(publication["publication_date"])
    publication_type = str(publication.get("type") or "")
    is_scholarly_article = publication_type in {"journal-article", "conference-paper"}
    authors = author_names(publication)
    citation = plain_text(publication.get("citation_plain") or publication.get("citation", ""))
    canonical = publication_url(publication)
    doi = str(publication.get("doi") or "").strip()
    external_url = str(publication.get("url") or "").strip()
    venue = str(publication.get("venue") or "").strip()
    volume = str(publication.get("volume") or "").strip()
    issue = str(publication.get("issue") or "").strip()
    pages = str(publication.get("pages") or "").strip()
    article_number = str(publication.get("article_number") or "").strip()
    contribution_note = str(publication.get("contribution_note") or "").strip()
    record_note = str(publication.get("note") or "").strip()
    keywords = publication.get("keywords") if isinstance(publication.get("keywords"), list) else []
    description = description_for(title, has_doi=bool(doi))

    schema: dict[str, object] = {
        "@context": "https://schema.org",
        "@type": "ScholarlyArticle" if is_scholarly_article else "CreativeWork",
        "@id": f"{canonical}#article",
        "url": canonical,
        "mainEntityOfPage": canonical,
        "headline": title,
        "name": title,
        "datePublished": publication_date,
        "author": [author_schema(name) for name in authors],
        "inLanguage": "en-CA",
    }
    container = citation_container(publication)
    if container:
        schema["isPartOf"] = container
    if keywords:
        schema["keywords"] = [str(keyword) for keyword in keywords]
    if pages:
        schema["pagination"] = pages
    elif article_number:
        schema["pagination"] = article_number
    if doi:
        schema["identifier"] = {"@type": "PropertyValue", "propertyID": "DOI", "value": doi}
    if external_url:
        schema["sameAs"] = external_url

    external_label = plain_text(publication.get("link_label")) or ("DOI" if doi else "Source")
    external_link = (
        f'<a class="button primary" href="{esc(external_url, attribute=True)}" '
        f'target="_blank" rel="noopener noreferrer" aria-label="{esc(external_label, attribute=True)} '
        f'(opens in a new tab)">{esc(external_label)}</a>'
        if external_url
        else ""
    )
    article_published_meta = (
        f'\n  <meta property="article:published_time" content="{esc(publication_date, attribute=True)}">'
        if re.fullmatch(r"\d{4}-\d{2}-\d{2}", publication_date)
        else ""
    )
    scholarly_meta = ""
    if is_scholarly_article:
        scholarly_meta = (
            f'  <meta name="citation_title" content="{esc(title, attribute=True)}">\n'
            f'{citation_meta(publication)}\n'
            f'  <meta name="citation_publication_date" content="{esc(scholar_date(publication_date), attribute=True)}">'
        )
        online_date = str(publication.get("online_date") or "").strip()
        if online_date:
            scholarly_meta += (
                f'\n  <meta name="citation_online_date" content="{esc(scholar_date(online_date), attribute=True)}">'
            )
    detail_rows = [
        f"<div><dt>Year</dt><dd>{year}</dd></div>",
        f"<div><dt>Status</dt><dd>{esc(publication.get('status'))}</dd></div>",
    ]
    if venue:
        detail_rows.append(f"<div><dt>Venue</dt><dd>{esc(venue)}</dd></div>")
    if volume:
        detail_rows.append(f"<div><dt>Volume</dt><dd>{esc(volume)}</dd></div>")
    if issue:
        detail_rows.append(f"<div><dt>Issue</dt><dd>{esc(issue)}</dd></div>")
    if pages:
        detail_rows.append(f"<div><dt>Pages</dt><dd>{esc(pages)}</dd></div>")
    if article_number:
        detail_rows.append(f"<div><dt>Article</dt><dd>{esc(article_number)}</dd></div>")
    if doi:
        detail_rows.append(
            f'<div><dt>DOI</dt><dd><a href="https://doi.org/{esc(doi, attribute=True)}">{esc(doi)}</a></dd></div>'
        )
    detail_rows.append(
        f"<div><dt>Last verified</dt><dd>{esc(publication.get('last_verified'))}</dd></div>"
    )
    topics_html = (
        '<section class="topics" aria-labelledby="topics-heading"><h2 id="topics-heading">Research topics</h2>'
        f'<ul role="list">{"".join(f"<li>{esc(keyword)}</li>" for keyword in keywords)}</ul></section>'
        if keywords
        else ""
    )

    page = f'''{GENERATED_MARKER}
<!doctype html>
<html lang="en-CA">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(title)} | Ramtin Mojtahedi</title>
  <meta name="description" content="{esc(description, attribute=True)}">
  <meta name="author" content="Dr. Ramtin Mojtahedi">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
{scholarly_meta}
  <link rel="canonical" href="{canonical}">
  <link rel="author" href="{ORCID_URL}">
  <link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="/assets/search-pages.css?v=20260802">
  <meta property="og:type" content="article">
  <meta property="og:url" content="{canonical}">
  <meta property="og:title" content="{esc(title, attribute=True)}">
  <meta property="og:description" content="{esc(description, attribute=True)}">{article_published_meta}
  {json_script(schema)}
</head>
<body>
  <a class="skip-link" href="#main-content">Skip to publication record</a>
  <header class="site-header">
    <a class="identity" href="/">RM <span>Dr. Ramtin Mojtahedi</span></a>
    <nav aria-label="Publication navigation">
      <a href="/">Portfolio</a>
      <a href="/publications/">All publications</a>
      <a href="{ORCID_URL}" rel="me">ORCID</a>
    </nav>
  </header>
  <main id="main-content">
    <article class="record">
      <p class="eyebrow">{esc(publication.get('status'))} · {year}</p>
      <h1>{esc(title)}</h1>
      <p class="authors">{esc(', '.join(authors))}</p>
      {f'<p class="contribution-note">{esc(contribution_note)}</p>' if contribution_note else ''}
      <p class="citation">{esc(citation)}</p>
      {f'<p class="record-note">{esc(record_note)}</p>' if record_note else ''}
      <div class="actions">{external_link}</div>
      <section class="record-details" aria-labelledby="record-details-heading">
        <h2 id="record-details-heading">Publication record</h2>
        <dl>{''.join(detail_rows)}</dl>
      </section>
      {topics_html}
      <p class="portfolio-note">This bibliographic page is part of <a href="/">Dr. Ramtin Mojtahedi’s medical AI research portfolio</a>.</p>
    </article>
  </main>
  <footer>Research portfolio record · <a href="/publications/">Browse all publications</a></footer>
</body>
</html>
'''
    return "\n".join(line.rstrip() for line in page.splitlines()) + "\n"


def publications_index(publications: list[dict[str, object]]) -> str:
    cards: list[str] = []
    item_list: list[dict[str, object]] = []
    for position, publication in enumerate(publications, start=1):
        canonical = publication_url(publication)
        authors = ", ".join(author_names(publication))
        citation = plain_text(publication.get("citation_plain") or publication.get("citation", ""))
        cards.append(
            f'''<li class="paper">
  <div class="paper-meta"><span>{int(publication['year'])}</span><span>{esc(publication.get('status'))}</span></div>
  <h2><a href="/publications/{esc(publication['id'], attribute=True)}/">{esc(publication['title'])}</a></h2>
  <p class="authors">{esc(authors)}</p>
  <p>{esc(citation)}</p>
</li>'''
        )
        item_list.append(
            {
                "@type": "ListItem",
                "position": position,
                "url": canonical,
                "name": str(publication["title"]),
            }
        )

    schema = {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "@id": f"{BASE_URL}/publications/#page",
        "url": f"{BASE_URL}/publications/",
        "name": "Publications and scholarly work by Dr. Ramtin Mojtahedi",
        "description": "Verified publication records for Dr. Ramtin Mojtahedi, medical AI researcher.",
        "about": {"@id": PERSON_ID},
        "mainEntity": {"@type": "ItemList", "numberOfItems": len(publications), "itemListElement": item_list},
        "inLanguage": "en-CA",
    }
    latest = max(str(publication.get("last_verified") or "") for publication in publications)
    return f'''{GENERATED_MARKER}
<!doctype html>
<html lang="en-CA">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Publications | Dr. Ramtin Mojtahedi, Medical AI Researcher</title>
  <meta name="description" content="Verified publications by Dr. Ramtin Mojtahedi in medical AI, imaging, segmentation, foundation models, and clinical prediction.">
  <meta name="author" content="Dr. Ramtin Mojtahedi">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
  <link rel="canonical" href="{BASE_URL}/publications/">
  <link rel="author" href="{ORCID_URL}">
  <link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="/assets/search-pages.css?v=20260802">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{BASE_URL}/publications/">
  <meta property="og:title" content="Publications | Dr. Ramtin Mojtahedi">
  <meta property="og:description" content="Verified research publications in medical AI, imaging, segmentation, foundation models, and clinical prediction.">
  {json_script(schema)}
</head>
<body>
  <a class="skip-link" href="#main-content">Skip to publication records</a>
  <header class="site-header">
    <a class="identity" href="/">RM <span>Dr. Ramtin Mojtahedi</span></a>
    <nav aria-label="Publication navigation"><a href="/">Portfolio</a><a href="{ORCID_URL}" rel="me">ORCID</a></nav>
  </header>
  <main id="main-content">
    <section class="collection">
      <p class="eyebrow">Research bibliography</p>
      <h1>Publications and scholarly work</h1>
      <p class="lede">{len(publications)} publication records spanning medical imaging, artificial intelligence, clinical prediction, segmentation, and biomedical engineering.</p>
      <ul class="paper-list" role="list">{''.join(cards)}</ul>
    </section>
  </main>
  <footer>Publication metadata last checked {esc(latest)} · <a href="/">Return to the portfolio</a></footer>
</body>
</html>
'''


def sitemap(publications: list[dict[str, object]]) -> str:
    urls = [f"{BASE_URL}/", f"{BASE_URL}/publications/"]
    urls.extend(publication_url(publication) for publication in publications)
    nodes = "\n".join(f"  <url>\n    <loc>{esc(url)}</loc>\n  </url>" for url in urls)
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{nodes}
</urlset>
'''


def indexnow_manifest(publications: list[dict[str, object]]) -> str:
    payload = {
        "host": "ramtin-mojtahedi.github.io",
        "key": INDEXNOW_KEY,
        "keyLocation": f"{BASE_URL}/{INDEXNOW_KEY}.txt",
        "urlList": [
            f"{BASE_URL}/",
            f"{BASE_URL}/publications/",
            *(publication_url(publication) for publication in publications),
        ],
    }
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def expected_files(publications: list[dict[str, object]]) -> dict[Path, str]:
    files = {
        PUBLICATIONS_DIR / "index.html": publications_index(publications),
        SITEMAP_FILE: sitemap(publications),
        INDEXNOW_FILE: indexnow_manifest(publications),
    }
    files.update(
        {
            PUBLICATIONS_DIR / str(publication["id"]) / "index.html": publication_page(publication)
            for publication in publications
        }
    )
    return files


def validate(publications: list[dict[str, object]]) -> None:
    if not publications:
        raise RuntimeError("No publication records found.")
    ids = [str(publication.get("id") or "") for publication in publications]
    if len(ids) != len(set(ids)) or any(not re.fullmatch(r"[a-z0-9-]+", value) for value in ids):
        raise RuntimeError("Publication ids must be unique URL-safe slugs.")
    if not INDEXNOW_KEY_FILE.is_file() or INDEXNOW_KEY_FILE.read_text(encoding="utf-8").strip() != INDEXNOW_KEY:
        raise RuntimeError("The IndexNow key file is missing or does not match the manifest key.")
    for publication in publications:
        missing = [
            field
            for field in ("id", "title", "year", "publication_date", "authors_html", "citation", "status")
            if not publication.get(field)
        ]
        if missing:
            raise RuntimeError(f"{publication.get('id', '<unknown>')}: missing {', '.join(missing)}")
        date = str(publication["publication_date"])
        if not re.fullmatch(r"\d{4}(?:-\d{2}-\d{2})?", date):
            raise RuntimeError(f"{publication['id']}: publication date must be a verified year or ISO date")
        if abs(int(date[:4]) - int(publication["year"])) > 1:
            raise RuntimeError(f"{publication['id']}: publication date is inconsistent with the conference year")
        if not author_names(publication):
            raise RuntimeError(f"{publication['id']}: no authors could be parsed")


def unexpected_pages(files: dict[Path, str]) -> list[Path]:
    return sorted(path for path in PUBLICATIONS_DIR.glob("*/index.html") if path not in files)


def prune_orphans(files: dict[Path, str]) -> None:
    for path in unexpected_pages(files):
        content = path.read_text(encoding="utf-8")
        siblings = list(path.parent.iterdir())
        if GENERATED_MARKER not in content or siblings != [path]:
            raise RuntimeError(f"Refusing to remove non-generated publication content: {path.relative_to(ROOT)}")
        path.unlink()
        path.parent.rmdir()
        print(f"Removed obsolete generated page: {path.relative_to(ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are missing or stale")
    args = parser.parse_args()

    publications = json.loads(PUBLICATIONS_FILE.read_text(encoding="utf-8"))
    validate(publications)
    files = expected_files(publications)

    if args.check:
        stale = [
            str(path.relative_to(ROOT))
            for path, content in files.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            print("Stale or missing generated search files:", file=sys.stderr)
            print("\n".join(f"- {path}" for path in stale), file=sys.stderr)
            return 1
        unexpected = [str(path.relative_to(ROOT)) for path in unexpected_pages(files)]
        if unexpected:
            print("Unexpected generated publication pages:", file=sys.stderr)
            print("\n".join(f"- {path}" for path in unexpected), file=sys.stderr)
            return 1
        print(f"Verified {len(publications)} publication pages, the publication index, sitemap, and IndexNow manifest.")
        return 0

    prune_orphans(files)
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    print(f"Built {len(publications)} publication pages, publications/index.html, sitemap.xml, and indexnow.json.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
