#!/usr/bin/env python3
"""Build scholarly pages, identity pages, citation exports, feeds, and search manifests."""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path
from urllib.parse import quote_plus, unquote, urlparse


ROOT = Path(__file__).resolve().parents[1]
PUBLICATIONS_FILE = ROOT / "_data" / "publications.json"
METRICS_FILE = ROOT / "_data" / "site_metrics.json"
PUBLICATIONS_DIR = ROOT / "publications"
ABOUT_DIR = ROOT / "about"
RESEARCH_DIR = ROOT / "research"
PUBLICATIONS_EXPORT_FILE = ROOT / "publications.json"
BIBTEX_FILE = ROOT / "publications.bib"
ATOM_FILE = ROOT / "publications.atom.xml"
SCHOLARLY_PAGES_FILE = ROOT / "scholarly-pages.json"
SITEMAP_FILE = ROOT / "sitemap.xml"
INDEXNOW_FILE = ROOT / "indexnow.json"

BASE_URL = "https://ramtin-mojtahedi.github.io"
PERSON_ID = f"{BASE_URL}/#person"
ORCID_URL = "https://orcid.org/0000-0002-3953-3256"
GOOGLE_SCHOLAR_URL = "https://scholar.google.com/citations?user=KjUrlGUAAAAJ&hl=en"
SAGE_LAB_URL = "https://sagelabuhn.ca/our-team/"
SIMPSON_LAB_URL = "https://labs.cs.queensu.ca/simpsonlab/members/ramtin-mojtahedi/"
QUEENS_CONVOCATION_URL = (
    "https://www.queensu.ca/registrar/sites/uregwww/files/uploaded_files/pdfs/"
    "Spring%202026%20Convocation/Queens%20-%202026%20Spring%20Convocation%20-%20June%20-%20Accessible.pdf"
)
QUEENS_AWARDS_URL = (
    "https://www.cs.queensu.ca/news/2024/07/18/"
    "ramtin-mojtahedi-was-recognized-by-major-graduate-student-awards/"
)
PROFILE_IMAGE_URL = f"{BASE_URL}/assets/ramtin-graduation.svg"
SOCIAL_IMAGE_URL = "https://avatars.githubusercontent.com/u/85639926?v=4"
PERSON_SAME_AS = [
    ORCID_URL,
    "https://github.com/Ramtin-Mojtahedi",
    "https://www.linkedin.com/in/ramtin-mojtahedi/",
    GOOGLE_SCHOLAR_URL,
    SAGE_LAB_URL,
    SIMPSON_LAB_URL,
]
INDEXNOW_KEY = "898f0caec5d8b22a095db2a4afa88722"
INDEXNOW_KEY_FILE = ROOT / f"{INDEXNOW_KEY}.txt"
GENERATED_MARKER = "<!-- Generated by scripts/build_search_pages.py; do not edit. -->"


TYPE_LABELS = {
    "journal-article": "Journal article",
    "conference-paper": "Conference paper",
    "conference-abstract": "Conference abstract",
    "conference-presentation": "Conference presentation",
    "dissertation": "Doctoral dissertation",
}

def esc(value: object, *, attribute: bool = False) -> str:
    return html.escape(str(value or ""), quote=attribute)


def plain_text(value: object) -> str:
    text = str(value or "")
    text = re.sub(r"<sup\b[^>]*>.*?</sup>", "", text, flags=re.IGNORECASE | re.DOTALL)
    text = re.sub(r"<[^>]+>", "", text)
    return re.sub(r"\s+", " ", html.unescape(text)).strip()


def author_names(publication: dict[str, object]) -> list[str]:
    names = publication.get("authors")
    if isinstance(names, list) and all(isinstance(name, str) and name.strip() for name in names):
        return [name.strip() for name in names]
    text = plain_text(publication.get("authors_html", "")).rstrip(".")
    text = re.sub(r",?\s+and\s+", ", ", text, flags=re.IGNORECASE)
    return [part.strip().rstrip(".") for part in text.split(",") if part.strip()]


def citation_author_names(publication: dict[str, object]) -> list[str]:
    names = publication.get("citation_authors")
    if isinstance(names, list) and all(isinstance(name, str) and name.strip() for name in names):
        return [name.strip() for name in names]
    return author_names(publication)


def formatted_citation(publication: dict[str, object]) -> str:
    names = author_names(publication)
    if len(names) > 2:
        authors = ", ".join(names[:-1]) + ", and " + names[-1]
    elif len(names) == 2:
        authors = " and ".join(names)
    else:
        authors = names[0] if names else ""
    title = plain_text(publication.get("title"))
    source = plain_text(publication.get("citation_plain") or publication.get("citation")).rstrip(".")
    parts = [f"{authors}." if authors else "", f'“{title}.”' if title else "", f"{source}." if source else ""]
    doi = str(publication.get("doi") or "").strip()
    source_url = str(publication.get("url") or "").strip()
    if doi:
        parts.append(f"https://doi.org/{doi}")
    elif source_url:
        parts.append(source_url)
    return " ".join(part for part in parts if part)



def is_ramtin(name: str) -> bool:
    normalized = re.sub(r"[^a-z]", "", name.lower())
    return "mojtahedi" in normalized or normalized in {
        "rmsaffari",
        "ramtinmojtahedisaffari",
    }


def author_schema(name: str) -> dict[str, object]:
    if is_ramtin(name):
        return {
            "@type": "Person",
            "@id": PERSON_ID,
            "name": name,
            "alternateName": ["Ramtin Mojtahedi", "Ramtin Mojtahedi Saffari", "R. M. Saffari"],
            "url": f"{BASE_URL}/about/",
            "sameAs": PERSON_SAME_AS,
        }
    return {"@type": "Person", "name": name}


def truncate(value: str, limit: int = 158) -> str:
    if len(value) <= limit:
        return value
    shortened = value[: limit - 1].rsplit(" ", 1)[0].rstrip(" ,;:-")
    return shortened + "…"


def description_for(
    title: str,
    *,
    has_doi: bool,
    abstract: str = "",
    venue: str = "",
    year: int | None = None,
) -> str:
    if abstract:
        return truncate(plain_text(abstract), 155)
    year_text = str(year) if year else "undated"
    detail = "citation, DOI, and access links" if has_doi else "citation and access links"
    full = f"{title} — {venue} ({year_text}). Verified {detail}." if venue else ""
    if full and len(full) <= 155:
        return full
    suffix = f" — {year_text}. Verified {detail}."
    available = 155 - len(suffix)
    if len(title) > available:
        short_title = title[: max(1, available - 1)].rsplit(" ", 1)[0].rstrip(" ,.;:-—") + "…"
    else:
        short_title = title
    return truncate(short_title + suffix, 155)


def publication_url(publication: dict[str, object]) -> str:
    return f"{BASE_URL}/publications/{publication['id']}/"


def publication_path(publication: dict[str, object]) -> str:
    return f"/publications/{publication['id']}/"


def latest_verified(publications: list[dict[str, object]]) -> str:
    values = [str(publication.get("last_verified") or "") for publication in publications]
    values = [value for value in values if value]
    if values:
        return max(values)
    return max(str(publication.get("publication_date") or "")[:10] for publication in publications)


def site_header(*, label: str) -> str:
    return f'''<header class="site-header">
    <a class="identity" href="/">RM <span>Dr. Ramtin Mojtahedi</span></a>
    <nav aria-label="{esc(label, attribute=True)}">
      <a href="/about/">About</a>
      <a href="/research/">Research</a>
      <a href="/publications/">Publications</a>
      <a href="{ORCID_URL}" rel="me">ORCID</a>
    </nav>
  </header>'''


def breadcrumb_schema(items: list[tuple[str, str]]) -> dict[str, object]:
    return {
        "@type": "BreadcrumbList",
        "itemListElement": [
            {
                "@type": "ListItem",
                "position": position,
                "name": name,
                "item": url,
            }
            for position, (name, url) in enumerate(items, start=1)
        ],
    }


def related_publications(
    publication: dict[str, object], publications: list[dict[str, object]], *, limit: int = 3
) -> list[dict[str, object]]:
    current_keywords = {str(value).casefold() for value in publication.get("keywords") or []}
    current_group = str(publication.get("group") or "").casefold()
    current_year = int(publication["year"])
    ranked: list[tuple[int, int, str, dict[str, object]]] = []
    for candidate in publications:
        if candidate["id"] == publication["id"]:
            continue
        candidate_keywords = {str(value).casefold() for value in candidate.get("keywords") or []}
        overlap = len(current_keywords & candidate_keywords)
        same_group = bool(current_group and current_group == str(candidate.get("group") or "").casefold())
        score = overlap * 10 + (4 if same_group else 0)
        if score:
            ranked.append(
                (score, -abs(current_year - int(candidate["year"])), str(candidate["title"]), candidate)
            )
    ranked.sort(key=lambda item: (-item[0], -item[1], item[2].casefold()))
    return [item[3] for item in ranked[:limit]]


def publication_feed_updated_at(publications: list[dict[str, object]]) -> str:
    if METRICS_FILE.is_file():
        try:
            metrics = json.loads(METRICS_FILE.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            metrics = {}
        timestamp = str(metrics.get("publication_sync_timestamp") or "").strip()
        if timestamp:
            return timestamp
    verified = latest_verified(publications)
    return f"{verified}T00:00:00Z" if re.fullmatch(r"\d{4}-\d{2}-\d{2}", verified) else verified


def json_script(payload: object) -> str:
    serialized = json.dumps(payload, ensure_ascii=False, indent=2).replace("</", "<\\/")
    return f'<script type="application/ld+json">\n{serialized}\n  </script>'


def scholar_date(value: object) -> str:
    date = str(value or "")
    return date.replace("-", "/") if re.fullmatch(r"\d{4}-\d{2}-\d{2}", date) else date


def citation_container(publication: dict[str, object]) -> dict[str, object] | None:
    venue = str(publication.get("venue") or "").strip()
    volume = str(publication.get("volume") or "").strip()
    publication_type = str(publication.get("type") or "")
    if not venue:
        return None
    if publication_type == "journal-article":
        periodical: dict[str, object] = {"@type": "Periodical", "name": venue}
        if volume:
            return {
                "@type": "PublicationVolume",
                "volumeNumber": volume,
                "isPartOf": periodical,
            }
        return periodical
    if volume:
        return {
            "@type": "PublicationVolume",
            "volumeNumber": volume,
            "isPartOf": {"@type": "CreativeWork", "name": venue},
        }
    return {"@type": "CreativeWork", "name": venue}


def citation_meta(publication: dict[str, object]) -> str:
    publication_type = str(publication.get("type") or "")
    venue = str(publication.get("venue") or "").strip()
    volume = str(publication.get("volume") or "").strip()
    issue = str(publication.get("issue") or "").strip()
    pages = str(publication.get("pages") or "").strip()
    article_number = str(publication.get("article_number") or "").strip()
    doi = str(publication.get("doi") or "").strip()
    citation_pdf_url = str(publication.get("citation_pdf_url") or "").strip()
    publisher = str(publication.get("publisher") or "").strip()
    keywords = publication.get("keywords") if isinstance(publication.get("keywords"), list) else []
    lines = [
        f'  <meta name="citation_author" content="{esc(name, attribute=True)}">'
        for name in citation_author_names(publication)
    ]
    lines.append('  <meta name="citation_language" content="en">')
    if venue:
        if publication_type == "journal-article":
            field = "citation_journal_title"
        elif publication_type == "dissertation":
            field = "citation_dissertation_institution"
        else:
            field = "citation_conference_title"
        lines.append(f'  <meta name="{field}" content="{esc(venue, attribute=True)}">')
    if volume:
        lines.append(f'  <meta name="citation_volume" content="{esc(volume, attribute=True)}">')
    if issue:
        lines.append(f'  <meta name="citation_issue" content="{esc(issue, attribute=True)}">')
    if pages:
        page_parts = re.split(r"\s*[-–—]\s*", pages, maxsplit=1)
        lines.append(f'  <meta name="citation_firstpage" content="{esc(page_parts[0], attribute=True)}">')
        if len(page_parts) == 2:
            lines.append(f'  <meta name="citation_lastpage" content="{esc(page_parts[1], attribute=True)}">')
    elif article_number:
        lines.append(f'  <meta name="citation_firstpage" content="{esc(article_number, attribute=True)}">')
    if doi:
        lines.append(f'  <meta name="citation_doi" content="{esc(doi, attribute=True)}">')
    if publisher:
        lines.append(f'  <meta name="citation_publisher" content="{esc(publisher, attribute=True)}">')
    if keywords:
        lines.append(
            f'  <meta name="citation_keywords" content="{esc("; ".join(str(value) for value in keywords), attribute=True)}">'
        )
    if citation_pdf_url:
        lines.append(
            f'  <meta name="citation_pdf_url" content="{esc(citation_pdf_url, attribute=True)}">'
        )
    return "\n".join(lines)


def bibtex_key(publication: dict[str, object]) -> str:
    explicit = str(publication.get("bibtex_key") or "").strip()
    if explicit:
        return explicit
    words = re.findall(r"[A-Za-z0-9]+", plain_text(publication.get("title")))[:4]
    title_key = "".join(word[:1].upper() + word[1:] for word in words)
    return f"Mojtahedi{publication.get('year')}{title_key or publication.get('id')}"


def bibtex_type(publication: dict[str, object]) -> str:
    explicit = str(publication.get("bibtex_type") or "").strip().lower()
    if explicit:
        return explicit
    return {
        "journal-article": "article",
        "conference-paper": "inproceedings",
        "dissertation": "phdthesis",
    }.get(str(publication.get("type") or ""), "misc")


def bibtex_text(value: object) -> str:
    text = plain_text(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    return "".join(replacements.get(character, character) for character in text)


def bibtex_entry(publication: dict[str, object]) -> str:
    entry_type = bibtex_type(publication)
    fields: list[tuple[str, object]] = [
        ("author", " and ".join(author_names(publication))),
        ("title", publication.get("title")),
        ("year", publication.get("year")),
    ]
    if entry_type == "article":
        fields.extend(
            [
                ("journal", publication.get("venue")),
                ("volume", publication.get("volume")),
                ("number", publication.get("issue")),
                ("pages", publication.get("pages")),
                ("eid", publication.get("article_number")),
            ]
        )
    elif entry_type == "inproceedings":
        fields.extend(
            [
                ("booktitle", publication.get("venue")),
                ("volume", publication.get("volume")),
                ("pages", publication.get("pages")),
                ("publisher", publication.get("publisher")),
            ]
        )
    elif entry_type == "phdthesis":
        fields.extend(
            [
                ("school", publication.get("venue") or publication.get("publisher")),
                ("type", "Doctoral dissertation"),
            ]
        )
    else:
        fields.append(("howpublished", publication.get("venue")))
    fields.extend(
        [
            ("doi", publication.get("doi")),
            ("url", publication.get("url") or publication_url(publication)),
            ("note", publication.get("note")),
        ]
    )
    rendered_fields = []
    for name, value in fields:
        if not str(value or "").strip():
            continue
        escaped = bibtex_text(value)
        if name == "title":
            escaped = "{" + escaped + "}"
        rendered_fields.append(f"  {name} = {{{escaped}}}")
    body = ",\n".join(rendered_fields)
    return f"@{entry_type}{{{bibtex_key(publication)},\n{body}\n}}"


def ris_entry(publication: dict[str, object]) -> str:
    ris_type = {
        "journal-article": "JOUR",
        "conference-paper": "CPAPER",
        "conference-abstract": "CPAPER",
        "conference-presentation": "CONF",
        "dissertation": "THES",
    }.get(str(publication.get("type") or ""), "GEN")
    lines = [f"TY  - {ris_type}", f"TI  - {plain_text(publication.get('title'))}"]
    lines.extend(f"AU  - {name}" for name in author_names(publication))
    lines.append(f"PY  - {publication.get('year')}")
    publication_date = str(publication.get("publication_date") or "").strip()
    if publication_date:
        lines.append(f"DA  - {publication_date}")
    venue = plain_text(publication.get("venue"))
    if venue:
        lines.append(f"T2  - {venue}")
    if publication.get("volume"):
        lines.append(f"VL  - {plain_text(publication.get('volume'))}")
    if publication.get("issue"):
        lines.append(f"IS  - {plain_text(publication.get('issue'))}")
    pages = str(publication.get("pages") or "").strip()
    if pages:
        page_parts = re.split(r"\s*[-–—]\s*", pages, maxsplit=1)
        lines.append(f"SP  - {page_parts[0]}")
        if len(page_parts) == 2:
            lines.append(f"EP  - {page_parts[1]}")
    elif publication.get("article_number"):
        lines.append(f"SP  - {plain_text(publication.get('article_number'))}")
    if publication.get("doi"):
        lines.append(f"DO  - {plain_text(publication.get('doi'))}")
    lines.append(f"UR  - {publication.get('url') or publication_url(publication)}")
    lines.extend(
        f"KW  - {plain_text(keyword)}"
        for keyword in publication.get("keywords", [])
        if plain_text(keyword)
    )
    if publication.get("note"):
        lines.append(f"N1  - {plain_text(publication.get('note'))}")
    lines.append("ER  -")
    return "\n".join(lines) + "\n"

def publication_type_label(publication: dict[str, object]) -> str:
    publication_type = str(publication.get("type") or "")
    return TYPE_LABELS.get(publication_type, publication_type.replace("-", " ").title() or "Scholarly work")

def public_full_text_url(publication: dict[str, object]) -> str:
    return str(
        publication.get("citation_pdf_url")
        or publication.get("open_access_url")
        or publication.get("preprint_url")
        or publication.get("pmc_url")
        or ""
    ).strip()

def external_record_labels(publication: dict[str, object]) -> list[str]:
    labels: list[str] = []
    if publication.get("doi"):
        labels.append("DOI")
    elif publication.get("url"):
        source_label = re.sub(
            r"\s*[↗→]+\s*$", "", plain_text(publication.get("link_label") or "")
        ).strip()
        labels.append(source_label or "Source record")
    if publication.get("pubmed_url"):
        labels.append("PubMed")
    if publication.get("pmc_url"):
        labels.append("PMC")
    if publication.get("preprint_url"):
        labels.append("arXiv/preprint")
    if publication.get("institutional_url"):
        labels.append("Institution record")
    if publication.get("bibliography_url"):
        labels.append("Bibliography record")
    return labels

def record_overview(publication: dict[str, object]) -> str:
    publication_type = str(publication.get("type") or "")
    work_type = publication_type_label(publication).lower()
    year = int(publication["year"])
    venue = str(publication.get("venue") or "").strip()
    if publication_type == "conference-presentation":
        opening = f"This record documents a conference presentation at {venue} ({year})."
    elif publication_type == "conference-abstract":
        opening = f"This conference abstract is recorded in {venue} ({year})."
    elif publication_type == "dissertation":
        opening = f"This author-supplied record describes a doctoral dissertation associated with {venue} ({year})."
    elif venue:
        opening = f"This {work_type} is recorded in {venue} ({year})."
    else:
        opening = f"This {work_type} is catalogued for {year}."
    has_external_record = bool(publication.get("url") or external_record_labels(publication))
    has_artifact = bool(public_full_text_url(publication) or publication.get("code_url"))
    if has_external_record or has_artifact:
        closing = "This page consolidates verified bibliographic metadata and the external records or research artifacts listed here."
    else:
        closing = "No authoritative external record, public full text, or research repository has yet been verified for this entry."
    return f"{opening} {closing}"

def publication_metadata_export(
    publication: dict[str, object], publications: list[dict[str, object]]
) -> str:
    related = related_publications(publication, publications)
    payload = {
        "schema_version": 1,
        "record_url": publication_url(publication),
        "last_verified": publication.get("last_verified"),
        "profile": {
            "name": "Ramtin Mojtahedi",
            "orcid": ORCID_URL,
            "google_scholar": GOOGLE_SCHOLAR_URL,
            "website": f"{BASE_URL}/",
        },
        "publication": publication,
        "citation": {
            "plain_text": formatted_citation(publication),
            "bibtex": bibtex_entry(publication),
            "ris": ris_entry(publication),
        },
        "related_records": [
            {
                "title": item.get("title"),
                "year": item.get("year"),
                "url": publication_url(item),
            }
            for item in related
        ],
    }
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"

def action_links(publication: dict[str, object]) -> str:
    external_url = str(publication.get("url") or "").strip()
    open_access_url = str(publication.get("open_access_url") or "").strip()
    links: list[tuple[str, str, str]] = []
    seen: set[str] = set()

    def add(url: object, label: object, kind: str) -> None:
        href = str(url or "").strip()
        text = re.sub(r"\s*[↗→]+\s*$", "", plain_text(label)).strip()
        if not href or href in seen:
            return
        seen.add(href)
        links.append((href, text or "View source", kind))

    source_is_open = bool(external_url and external_url == open_access_url)
    source_label = (
        publication.get("open_access_label")
        if source_is_open
        else publication.get("link_label") or ("DOI" if publication.get("doi") else "Source")
    )
    add(external_url, source_label, "open" if source_is_open else "primary")
    add(
        open_access_url or publication.get("pmc_url"),
        publication.get("open_access_label") or "Open-access copy",
        "open",
    )
    add(publication.get("citation_pdf_url"), "Full-text PDF", "open")
    add(publication.get("preprint_url"), "Preprint", "open")
    add(publication.get("code_url"), publication.get("code_label") or "Code repository", "code")
    add(publication.get("pubmed_url"), "PubMed", "secondary")
    add(
        publication.get("institutional_url"),
        publication.get("institutional_label") or "Institution record",
        "secondary",
    )
    add(
        publication.get("bibliography_url"),
        publication.get("bibliography_label") or "Bibliography record",
        "secondary",
    )
    return "\n".join(
        f'<a class="button {kind}" href="{esc(url, attribute=True)}" target="_blank" '
        f'rel="noopener noreferrer" aria-label="{esc(label, attribute=True)} (opens in a new tab)">'
        f"{esc(label)} ↗</a>"
        for url, label, kind in links
    )



def publication_page(
    publication: dict[str, object], publications: list[dict[str, object]]
) -> str:
    title = str(publication["title"])
    year = int(publication["year"])
    publication_date = str(publication["publication_date"])
    publication_type = str(publication.get("type") or "")
    is_scholarly_article = publication_type in {
        "journal-article",
        "conference-paper",
        "conference-abstract",
    }
    schema_type = (
        "ScholarlyArticle"
        if is_scholarly_article
        else "Thesis"
        if publication_type == "dissertation"
        else "CreativeWork"
    )
    authors = author_names(publication)
    author_line_html = ", ".join(
        f'<strong class="profile-author">{esc(name)}</strong>' if is_ramtin(name) else esc(name)
        for name in authors
    )
    citation = plain_text(publication.get("citation_plain") or publication.get("citation", ""))
    reusable_citation = formatted_citation(publication)
    canonical = publication_url(publication)
    doi = str(publication.get("doi") or "").strip()
    external_url = str(publication.get("url") or "").strip()
    venue = str(publication.get("venue") or "").strip()
    volume = str(publication.get("volume") or "").strip()
    issue = str(publication.get("issue") or "").strip()
    pages = str(publication.get("pages") or "").strip()
    article_number = str(publication.get("article_number") or "").strip()
    contribution_note = str(publication.get("contribution_note") or "").strip()
    record_note = str(publication.get("note") or "").strip()
    abstract = plain_text(publication.get("abstract") or publication.get("summary"))
    abstract_heading = "Abstract" if publication.get("abstract") else "Research summary"
    publisher = str(publication.get("publisher") or "").strip()
    open_access_url = str(publication.get("open_access_url") or "").strip()
    open_access_license = str(publication.get("open_access_license") or "").strip()
    citation_pdf_url = str(publication.get("citation_pdf_url") or "").strip()
    preprint_url = str(publication.get("preprint_url") or "").strip()
    code_url = str(publication.get("code_url") or "").strip()
    pubmed_url = str(publication.get("pubmed_url") or "").strip()
    pmc_url = str(publication.get("pmc_url") or "").strip()
    institutional_url = str(publication.get("institutional_url") or "").strip()
    bibliography_url = str(publication.get("bibliography_url") or "").strip()
    sharing_notice = str(publication.get("sharing_notice") or "").strip()
    manuscript_terms_url = str(publication.get("manuscript_terms_url") or "").strip()
    keywords = publication.get("keywords") if isinstance(publication.get("keywords"), list) else []
    title_aliases = (
        publication.get("title_aliases") if isinstance(publication.get("title_aliases"), list) else []
    )
    description = description_for(
        title,
        has_doi=bool(doi),
        abstract=abstract,
        venue=venue,
        year=year,
    )
    entry = bibtex_entry(publication)
    type_label = publication_type_label(publication)
    full_text_url = public_full_text_url(publication)
    external_labels = external_record_labels(publication)
    related = related_publications(publication, publications)

    schema: dict[str, object] = {
        "@context": "https://schema.org",
        "@type": schema_type,
        "@id": f"{canonical}#article",
        "url": canonical,
        "mainEntityOfPage": canonical,
        "headline": title,
        "name": title,
        "datePublished": publication_date,
        "author": [author_schema(name) for name in authors],
        "inLanguage": "en",
        "genre": type_label,
        "creativeWorkStatus": str(publication.get("status") or ""),
    }
    if publication_type == "dissertation":
        schema["inSupportOf"] = "Doctor of Philosophy (PhD)"
    container = citation_container(publication)
    if container:
        schema["isPartOf"] = container
    if keywords:
        schema["keywords"] = [str(keyword) for keyword in keywords]
        schema["about"] = [
            {"@type": "DefinedTerm", "name": str(keyword)} for keyword in keywords
        ]
    if title_aliases:
        schema["alternateName"] = [str(alias) for alias in title_aliases]
    if abstract:
        schema["abstract"] = abstract
        schema["description"] = abstract
    if publisher:
        schema["publisher"] = {"@type": "Organization", "name": publisher}
    if pages:
        schema["pagination"] = pages
    elif article_number:
        schema["pagination"] = article_number
    if doi:
        schema["identifier"] = {"@type": "PropertyValue", "propertyID": "DOI", "value": doi}
    same_as = list(
        dict.fromkeys(
            value
            for value in (
                external_url,
                preprint_url,
                pubmed_url,
                pmc_url,
                institutional_url,
                bibliography_url,
            )
            if value
        )
    )
    if same_as:
        schema["sameAs"] = same_as[0] if len(same_as) == 1 else same_as
    if code_url:
        schema["subjectOf"] = {
            "@type": "CreativeWork",
            "name": str(publication.get("code_label") or "Related research repository"),
            "url": code_url,
        }
    if open_access_url or citation_pdf_url or publication.get("preprint_url"):
        schema["isAccessibleForFree"] = True
    open_access_license_url = str(publication.get("open_access_license_url") or "").strip()
    if manuscript_terms_url or open_access_license_url:
        schema["license"] = manuscript_terms_url or open_access_license_url
    if citation_pdf_url:
        schema["encoding"] = {
            "@type": "MediaObject",
            "contentUrl": citation_pdf_url,
            "encodingFormat": "application/pdf",
        }

    actions = action_links(publication)
    article_published_meta = (
        f'\n  <meta property="article:published_time" content="{esc(publication_date, attribute=True)}">'
        if re.fullmatch(r"\d{4}-\d{2}-\d{2}", publication_date)
        else ""
    )
    scholarly_meta = (
        f'  <meta name="citation_title" content="{esc(title, attribute=True)}">\n'
        f'{citation_meta(publication)}\n'
        f'  <meta name="citation_publication_date" content="{esc(scholar_date(publication_date), attribute=True)}">'
    )
    online_date = str(publication.get("online_date") or "").strip()
    if online_date:
        scholarly_meta += (
            f'\n  <meta name="citation_online_date" content="{esc(scholar_date(online_date), attribute=True)}">'
        )
    detail_rows = [
        f"<div><dt>Work type</dt><dd>{esc(type_label)}</dd></div>",
        f"<div><dt>Year</dt><dd>{year}</dd></div>",
        f"<div><dt>Publication date</dt><dd>{esc(publication_date)}</dd></div>",
        f"<div><dt>Status</dt><dd>{esc(publication.get('status'))}</dd></div>",
    ]
    if venue:
        detail_rows.append(f"<div><dt>Venue</dt><dd>{esc(venue)}</dd></div>")
    if publisher:
        detail_rows.append(f"<div><dt>Publisher</dt><dd>{esc(publisher)}</dd></div>")
    if volume:
        detail_rows.append(f"<div><dt>Volume</dt><dd>{esc(volume)}</dd></div>")
    if issue:
        detail_rows.append(f"<div><dt>Issue</dt><dd>{esc(issue)}</dd></div>")
    if pages:
        detail_rows.append(f"<div><dt>Pages</dt><dd>{esc(pages)}</dd></div>")
    if article_number:
        detail_rows.append(f"<div><dt>Article</dt><dd>{esc(article_number)}</dd></div>")
    if doi:
        detail_rows.append(
            f'<div><dt>DOI</dt><dd><a href="https://doi.org/{esc(doi, attribute=True)}">{esc(doi)}</a></dd></div>'
        )
    detail_rows.append(
        f"<div><dt>Last verified</dt><dd>{esc(publication.get('last_verified'))}</dd></div>"
    )
    topics_html = (
        '<section class="topics" aria-labelledby="topics-heading"><h2 id="topics-heading">Research topics</h2>'
        f'<ul role="list">{"".join(f"<li>{esc(keyword)}</li>" for keyword in keywords)}</ul></section>'
        if keywords
        else ""
    )
    abstract_html = (
        f'<section class="abstract" aria-labelledby="abstract-heading"><h2 id="abstract-heading">'
        f"{esc(abstract_heading)}</h2><p>{esc(abstract)}</p></section>"
        if abstract
        else ""
    )
    aliases_html = (
        '<section class="title-variants" aria-labelledby="title-variants-heading">'
        '<h2 id="title-variants-heading">Title variants</h2><ul role="list">'
        + "".join(f"<li>{esc(alias)}</li>" for alias in title_aliases)
        + "</ul></section>"
        if title_aliases
        else ""
    )
    license_html = ""
    if open_access_license or manuscript_terms_url:
        terms = esc(open_access_license) if open_access_license else "Publisher sharing terms"
        if manuscript_terms_url:
            terms += (
                f' · <a href="{esc(manuscript_terms_url, attribute=True)}" target="_blank" '
                f'rel="noopener noreferrer">Publisher terms ↗</a>'
            )
        license_html = f'<p class="license-note"><strong>Access terms:</strong> {terms}</p>'
    if sharing_notice:
        sharing_html = (
            '<aside class="sharing-notice"><strong>Version and sharing notice.</strong> '
            f'{esc(sharing_notice)}</aside>'
        )
    elif citation_pdf_url or preprint_url or open_access_license:
        sharing_html = (
            '<aside class="sharing-notice"><strong>Responsible access.</strong> This page identifies the '
            'specific public version and its access terms. Publisher-formatted files are not mirrored unless '
            'redistribution is expressly permitted.</aside>'
        )
    else:
        sharing_html = ""
    actions_html = (
        '<div class="actions">'
        f'{actions}'
        '<a class="button secondary" href="#cite">Cite this work</a>'
        '</div>'
    )
    encoded_title = quote_plus(title)
    keyword_meta = (
        f'\n  <meta name="keywords" content="{esc(", ".join(str(keyword) for keyword in keywords), attribute=True)}">'
        if keywords
        else ""
    )
    full_text_detail = (
        str(publication.get("open_access_label") or "").strip()
        or ("Author-hosted PDF" if citation_pdf_url else "")
        or ("Preprint available" if preprint_url else "")
        or ("PMC full text" if pmc_url else "")
        or "Publicly accessible copy"
    )
    availability_items = [
        (
            "Canonical source",
            "Authoritative source linked" if external_url else "No authoritative external record verified",
            bool(external_url),
        ),
        (
            "Public full text",
            full_text_detail if full_text_url else "No lawful public copy verified",
            bool(full_text_url),
        ),
        (
            "Research repository",
            "Repository linked" if code_url else "No public repository verified",
            bool(code_url),
        ),
        (
            "External records",
            ", ".join(external_labels) if external_labels else "Author catalog record only",
            bool(external_labels),
        ),
    ]
    availability_html = (
        '<aside class="availability-card" aria-labelledby="availability-heading">'
        '<div class="availability-heading"><p class="mini-kicker">Verified availability</p>'
        '<h2 id="availability-heading">Publication access</h2></div><ul role="list">'
        + "".join(
            f'<li data-state="{"available" if available else "pending"}"><span>{esc(label)}</span>'
            f'<strong>{esc(detail)}</strong></li>'
            for label, detail, available in availability_items
        )
        + f'</ul><p class="verification-date">Metadata checked {esc(publication.get("last_verified"))}</p></aside>'
    )
    def pipeline_step(
        number: str,
        label: str,
        title_text: str,
        detail_text: str,
        *,
        url: str = "",
        available: bool = True,
        internal: bool = False,
    ) -> str:
        if url:
            target = "" if internal else ' target="_blank" rel="noopener noreferrer"'
            title_html = f'<a href="{esc(url, attribute=True)}"{target}>{esc(title_text)}</a>'
        else:
            title_html = esc(title_text)
        state = "available" if available else "pending"
        return (
            f'<li data-state="{state}"><span class="pipeline-number">{esc(number)}</span>'
            f'<span class="pipeline-label">{esc(label)}</span>'
            f'<strong>{title_html}</strong><small>{esc(detail_text)}</small></li>'
        )

    source_title = "DOI / publisher record" if doi else (
        re.sub(r"\s*[↗→]+\s*$", "", plain_text(publication.get("link_label") or "Official source"))
        if external_url
        else "Curated author record"
    )
    reuse_url = code_url or institutional_url or bibliography_url
    if code_url:
        reuse_title = str(publication.get("code_label") or "Research repository")
        reuse_detail = "Linked code or research-artifact record"
    elif institutional_url:
        reuse_title = str(publication.get("institutional_label") or "Institution record")
        reuse_detail = "Verified institutional discovery record"
    elif bibliography_url:
        reuse_title = str(publication.get("bibliography_label") or "Bibliography record")
        reuse_detail = "Verified scholarly bibliography record"
    else:
        reuse_title = "No repository verified"
        reuse_detail = "A research repository will be linked only when verified"
    pipeline_html = (
        '<section class="discovery-pipeline" aria-labelledby="pipeline-heading">'
        '<div class="section-heading"><div><p class="section-kicker">Verified discovery path</p>'
        '<h2 id="pipeline-heading">Publication access pipeline</h2></div>'
        '<p>Follow the authoritative route from source to reuse.</p></div>'
        '<ol class="pipeline-flow">'
        + pipeline_step(
            "01", "Source", source_title,
            "Canonical external source" if external_url else "No external source verified yet",
            url=external_url, available=bool(external_url),
        )
        + pipeline_step(
            "02", "Read",
            full_text_detail if full_text_url else "No lawful public copy verified",
            "Publicly readable version" if full_text_url else "Use the source record or library access",
            url=full_text_url, available=bool(full_text_url),
        )
        + pipeline_step(
            "03", "Cite", "Citation files ready",
            "Formatted citation, BibTeX, RIS, and JSON", url="#cite", internal=True,
        )
        + pipeline_step(
            "04", "Explore", reuse_title, reuse_detail,
            url=reuse_url, available=bool(reuse_url),
        )
        + '</ol></section>'
    )
    overview_html = (
        '<section class="overview" aria-labelledby="overview-heading">'
        '<p class="section-kicker">Verified bibliographic overview</p>'
        '<h2 id="overview-heading">About this work</h2>'
        f'<p>{esc(record_overview(publication))}</p></section>'
    )
    related_html = (
        '<section class="related" aria-labelledby="related-heading">'
        '<div class="section-heading"><div><p class="section-kicker">Connected portfolio</p>'
        '<h2 id="related-heading">Related research</h2></div><a href="/publications/">View all {len(publications)} records</a></div>'
        '<div class="related-grid">'
        + "".join(
            f'<article><p class="related-meta">{esc(item.get("year"))} · {esc(publication_type_label(item))}</p>'
            f'<h3><a href="{esc(publication_path(item), attribute=True)}">{esc(item.get("title"))}</a></h3>'
            f'<p>{esc(plain_text(item.get("citation_plain") or item.get("citation")))}</p></article>'
            for item in related
        )
        + "</div></section>"
        if related
        else ""
    )
    position = next(
        index for index, item in enumerate(publications) if item.get("id") == publication.get("id")
    )
    newer = publications[position - 1] if position > 0 else None
    older = publications[position + 1] if position + 1 < len(publications) else None
    adjacent_links: list[str] = []
    if newer:
        adjacent_links.append(
            f'<a class="adjacent-link" href="{esc(publication_path(newer), attribute=True)}">'
            f'<span>Newer record</span><strong>{esc(newer.get("title"))}</strong></a>'
        )
    if older:
        adjacent_links.append(
            f'<a class="adjacent-link" href="{esc(publication_path(older), attribute=True)}">'
            f'<span>Earlier record</span><strong>{esc(older.get("title"))}</strong></a>'
        )
    adjacent_html = (
        '<nav class="adjacent-records" aria-label="Adjacent publication records">'
        + "".join(adjacent_links)
        + "</nav>"
        if adjacent_links
        else ""
    )
    share_mailto = (
        "mailto:?subject="
        + quote_plus(title)
        + "&body="
        + quote_plus(f"{reusable_citation}\n\nCanonical record: {canonical}")
    )

    page = f'''{GENERATED_MARKER}
<!doctype html>
<html lang="en-CA">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(title)} | Ramtin Mojtahedi</title>
  <meta name="description" content="{esc(description, attribute=True)}">
  <meta name="author" content="Dr. Ramtin Mojtahedi">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">{keyword_meta}
{scholarly_meta}
  <link rel="canonical" href="{canonical}">
  <link rel="author" href="{ORCID_URL}">
  <link rel="alternate" type="application/x-bibtex" title="BibTeX citation" href="{canonical}citation.bib">
  <link rel="alternate" type="application/x-research-info-systems" title="RIS citation" href="{canonical}citation.ris">\n  <link rel="alternate" type="application/atom+xml" title="Ramtin Mojtahedi publications" href="{BASE_URL}/publications.atom.xml">
  <link rel="alternate" type="application/json" title="Publication metadata" href="{canonical}metadata.json">
  <link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="/assets/search-pages.css?v=20260802-6">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="Ramtin Mojtahedi · Medical AI Research">
  <meta property="og:url" content="{canonical}">
  <meta property="og:title" content="{esc(title, attribute=True)}">
  <meta property="og:description" content="{esc(description, attribute=True)}">{article_published_meta}
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="{esc(title, attribute=True)}">
  <meta name="twitter:description" content="{esc(description, attribute=True)}">
  {json_script(schema)}
  <script src="/assets/scholarly-pages.js?v=20260802-2" defer></script>
</head>
<body>
  <a class="skip-link" href="#main-content">Skip to publication record</a>
  <header class="site-header">
    <a class="identity" href="/">RM <span>Dr. Ramtin Mojtahedi</span></a>
    <nav aria-label="Publication navigation">
      <a href="/">Portfolio</a>
      <a href="/publications/">All publications</a>
      <a href="{ORCID_URL}" rel="me">ORCID</a>
    </nav>
  </header>
  <main id="main-content">
    <article class="record">
      <nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Portfolio</a><span aria-hidden="true">/</span><a href="/publications/">Publications</a><span aria-hidden="true">/</span><span aria-current="page">{year}</span></nav>
      <header class="record-hero">
        <div class="record-hero-copy">
          <div class="record-badges"><span>{esc(type_label)}</span><span>{year}</span><span>{esc(publication.get('status'))}</span></div>
          <h1>{esc(title)}</h1>
          <p class="authors">{author_line_html}</p>
          {f'<p class="contribution-note">{esc(contribution_note)}</p>' if contribution_note else ''}
          <p class="citation">{esc(citation)}</p>
          {f'<p class="record-note">{esc(record_note)}</p>' if record_note else ''}
          {actions_html}
          {license_html}
        </div>
        {availability_html}
      </header>
      {pipeline_html}
      {abstract_html}
      {overview_html}
      <div class="record-information-grid">
        <section class="record-details" aria-labelledby="record-details-heading">
          <p class="section-kicker">Canonical metadata</p>
          <h2 id="record-details-heading">Publication record</h2>
          <dl>{''.join(detail_rows)}</dl>
        </section>
        <div class="record-taxonomy">
          {topics_html}
          {aliases_html}
        </div>
      </div>
      <section class="cite" id="cite" aria-labelledby="cite-heading">
        <div class="section-heading"><div><p class="section-kicker">Ready to reuse</p><h2 id="cite-heading">Cite this work</h2></div><a href="/publications.bib" download>Download all {len(publications)} citations</a></div>
        <p class="formatted-citation" id="plain-citation">{esc(reusable_citation)}</p>
        <div class="citation-toolbar" aria-label="Citation tools">
          <button type="button" class="utility-button" data-copy-target="#plain-citation">Copy formatted citation</button>
          <button type="button" class="utility-button" data-copy-target="#bibtex-entry">Copy BibTeX</button>
          <a class="utility-button" href="citation.bib" download>Download this BibTeX</a>
          <a class="utility-button" href="citation.ris" download>Download RIS</a>
          <a class="utility-button" href="https://scholar.google.com/scholar?q={encoded_title}" target="_blank" rel="noopener noreferrer">Find in Google Scholar ↗</a>
        </div>
        <p class="copy-status" data-copy-status aria-live="polite"></p>
        <pre><code id="bibtex-entry">{esc(entry)}</code></pre>
      </section>
      <section class="record-utilities" aria-labelledby="record-utilities-heading">
        <div><p class="section-kicker">Persistent discovery</p><h2 id="record-utilities-heading">Share and inspect this record</h2><p>Use the canonical page when sharing this work so citation metadata, access links, and future corrections stay together.</p></div>
        <div class="citation-toolbar">
          <button type="button" class="utility-button" data-copy-url="{esc(canonical, attribute=True)}">Copy canonical link</button>
          <button type="button" class="utility-button" data-share-url="{esc(canonical, attribute=True)}" data-share-title="{esc(title, attribute=True)}" data-share-text="{esc(reusable_citation, attribute=True)}">Share record</button>
          <a class="utility-button" href="{esc(share_mailto, attribute=True)}">Email record</a>
          <a class="utility-button" href="metadata.json">Machine-readable JSON</a>
        </div>
      </section>
      {related_html}
      {sharing_html}
      {adjacent_html}
      <p class="portfolio-note">Verified publication page in <a href="/">Dr. Ramtin Mojtahedi’s medical AI research portfolio</a>. Metadata corrections are made only from authoritative records.</p>
    </article>
  </main>
  <footer>Research portfolio record · <a href="/publications/">Browse all publications</a></footer>
</body>
</html>
'''
    return "\n".join(line.rstrip() for line in page.splitlines()) + "\n"



def publications_index(publications: list[dict[str, object]]) -> str:
    cards: list[str] = []
    item_list: list[dict[str, object]] = []
    for position, publication in enumerate(publications, start=1):
        canonical = publication_url(publication)
        authors = ", ".join(author_names(publication))
        citation = plain_text(publication.get("citation_plain") or publication.get("citation", ""))
        keywords = [plain_text(value) for value in publication.get("keywords", []) if plain_text(value)]
        work_type = publication_type_label(publication)
        access_value = "public" if public_full_text_url(publication) else "metadata"
        repository_value = "linked" if publication.get("code_url") else "none"
        search_text = " ".join(
            [str(publication.get("title") or ""), authors, citation, work_type, *keywords]
        ).casefold()
        badges = [str(publication.get("year")), str(publication.get("status") or "")]
        if publication.get("open_access_url") or publication.get("citation_pdf_url"):
            badges.append("Public full text")
        if publication.get("preprint_url"):
            badges.append("Preprint")
        if publication.get("code_url"):
            badges.append("Code")
        topics = (
            '<ul class="paper-topics" role="list">'
            + "".join(f"<li>{esc(keyword)}</li>" for keyword in keywords)
            + "</ul>"
            if keywords
            else ""
        )
        cards.append(
            f'''<li class="paper" data-publication-card data-year="{esc(publication.get('year'), attribute=True)}" data-type="{esc(str(publication.get('type') or ''), attribute=True)}" data-access="{access_value}" data-repository="{repository_value}" data-search="{esc(search_text, attribute=True)}">
  <div class="paper-meta">{"".join(f"<span>{esc(badge)}</span>" for badge in badges if badge)}</div>
  <h2><a href="/publications/{esc(publication['id'], attribute=True)}/">{esc(publication['title'])}</a></h2>
  <p class="authors">{esc(authors)}</p>
  <p>{esc(citation)}</p>
  {topics}
  <p class="paper-record-link"><a href="/publications/{esc(publication['id'], attribute=True)}/">Open the verified record <span aria-hidden="true">→</span></a></p>
</li>'''
        )
        item_list.append(
            {
                "@type": "ListItem",
                "position": position,
                "url": canonical,
                "name": str(publication["title"]),
            }
        )

    years = sorted({int(publication["year"]) for publication in publications}, reverse=True)
    publication_types = sorted(
        {str(publication.get("type") or "") for publication in publications},
        key=lambda value: TYPE_LABELS.get(value, value),
    )
    year_options = "".join(f'<option value="{year}">{year}</option>' for year in years)
    type_options = "".join(
        f'<option value="{esc(value, attribute=True)}">{esc(TYPE_LABELS.get(value, value.title()))}</option>'
        for value in publication_types
        if value
    )

    schema = {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "@id": f"{BASE_URL}/publications/#page",
        "url": f"{BASE_URL}/publications/",
        "name": "Publications and scholarly work by Dr. Ramtin Mojtahedi",
        "description": "Verified publication records for Dr. Ramtin Mojtahedi, medical AI researcher.",
        "about": {"@id": PERSON_ID},
        "mainEntity": {"@type": "ItemList", "numberOfItems": len(publications), "itemListElement": item_list},
        "inLanguage": "en-CA",
    }
    latest = latest_verified(publications)
    return f'''{GENERATED_MARKER}
<!doctype html>
<html lang="en-CA">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Publications | Dr. Ramtin Mojtahedi, Medical AI Researcher</title>
  <meta name="description" content="Verified publications by Dr. Ramtin Mojtahedi in medical AI, imaging, segmentation, foundation models, and clinical prediction.">
  <meta name="author" content="Dr. Ramtin Mojtahedi">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
  <link rel="canonical" href="{BASE_URL}/publications/">
  <link rel="author" href="{ORCID_URL}">
  <link rel="alternate" type="application/json" title="Publication data" href="/publications.json">
  <link rel="alternate" type="application/x-bibtex" title="Publication BibTeX" href="/publications.bib">\n  <link rel="alternate" type="application/atom+xml" title="Ramtin Mojtahedi publications" href="/publications.atom.xml">
  <link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="/assets/search-pages.css?v=20260802-6">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Ramtin Mojtahedi · Medical AI Research">
  <meta property="og:url" content="{BASE_URL}/publications/">
  <meta property="og:title" content="Publications | Dr. Ramtin Mojtahedi">
  <meta property="og:description" content="Verified research publications in medical AI, imaging, segmentation, foundation models, and clinical prediction.">
  <meta name="twitter:card" content="summary">
  {json_script(schema)}
  <script src="/assets/scholarly-pages.js?v=20260802-2" defer></script>
</head>
<body>
  <a class="skip-link" href="#main-content">Skip to publication records</a>
  <header class="site-header">
    <a class="identity" href="/">RM <span>Dr. Ramtin Mojtahedi</span></a>
    <nav aria-label="Publication navigation"><a href="/">Portfolio</a><a href="/about/">About</a><a href="/research/">Research</a><a href="/publications.bib" download>BibTeX</a><a href="/publications.json">JSON</a><a href="/publications.atom.xml">Atom</a><a href="{ORCID_URL}" rel="me">ORCID</a></nav>
  </header>
  <main id="main-content">
    <section class="collection">
      <p class="eyebrow">Research bibliography</p>
      <h1>Publications and scholarly work</h1>
      <p class="lede">{len(publications)} publication records spanning medical imaging, artificial intelligence, clinical prediction, segmentation, and biomedical engineering.</p>
      <p class="export-links"><a href="/research/">Browse by research theme</a> · <a href="/publications.bib" download>Download complete BibTeX</a> · <a href="/publications.json">Browse the JSON dataset</a> · <a href="/publications.atom.xml">Follow the Atom feed</a></p>
      <section class="library-tools" aria-labelledby="library-tools-heading">
        <div class="library-tools-heading"><p class="section-kicker">Explore the portfolio</p><h2 id="library-tools-heading">Find a publication</h2><p>Search verified titles, authors, venues, and research topics. Filters never hide records from search crawlers.</p></div>
        <form class="publication-filters" data-publication-filters>
          <label class="search-field"><span>Search</span><input type="search" name="query" placeholder="e.g., liver segmentation or SimSiam" autocomplete="off"></label>
          <label><span>Year</span><select name="year"><option value="">All years</option>{year_options}</select></label>
          <label><span>Type</span><select name="type"><option value="">All types</option>{type_options}</select></label>
          <label><span>Availability</span><select name="access"><option value="">All records</option><option value="public">Public full text</option><option value="metadata">Metadata/publisher record</option><option value="repository">Research repository linked</option></select></label>
          <button type="button" class="utility-button" data-clear-filters>Clear filters</button>
        </form>
        <p class="result-count" data-result-count aria-live="polite">Showing all {len(publications)} records</p>
      </section>
      <ul class="paper-list" role="list">{''.join(cards)}</ul>
      <p class="no-results" data-no-results hidden>No records match those filters. Clear the filters or try a broader topic.</p>
    </section>
  </main>
  <footer>Publication metadata last checked {esc(latest)} · <a href="/">Return to the portfolio</a></footer>
</body>
</html>
'''

def about_page(publications: list[dict[str, object]]) -> str:
    canonical = f"{BASE_URL}/about/"
    modified = latest_verified(publications)
    person = {
        "@type": "Person",
        "@id": PERSON_ID,
        "name": "Ramtin Mojtahedi",
        "givenName": "Ramtin",
        "familyName": "Mojtahedi",
        "alternateName": ["Dr. Ramtin Mojtahedi", "Ramtin Mojtahedi Saffari", "R. M. Saffari"],
        "honorificPrefix": "Dr.",
        "honorificSuffix": "Ph.D.",
        "url": f"{BASE_URL}/",
        "mainEntityOfPage": {"@id": f"{canonical}#page"},
        "image": {
            "@type": "ImageObject",
            "url": PROFILE_IMAGE_URL,
            "caption": "Portrait of Dr. Ramtin Mojtahedi",
        },
        "jobTitle": "Postdoctoral Researcher",
        "description": (
            "Medical AI researcher working in medical imaging, segmentation, foundation models, "
            "and multimodal clinical prediction."
        ),
        "worksFor": {
            "@type": "Organization",
            "name": "University Health Network",
            "url": "https://www.uhn.ca/",
        },
        "alumniOf": {
            "@type": "CollegeOrUniversity",
            "name": "Queen's University",
            "url": "https://www.queensu.ca/",
        },
        "hasCredential": {
            "@type": "EducationalOccupationalCredential",
            "name": "Doctor of Philosophy in Computing",
            "credentialCategory": "Doctoral degree",
            "recognizedBy": {
                "@type": "CollegeOrUniversity",
                "name": "Queen's University",
                "url": "https://www.queensu.ca/",
            },
        },
        "identifier": {
            "@type": "PropertyValue",
            "propertyID": "ORCID",
            "value": "0000-0002-3953-3256",
            "url": ORCID_URL,
        },
        "sameAs": PERSON_SAME_AS,
        "subjectOf": [
            {"@type": "CreativeWork", "url": QUEENS_CONVOCATION_URL},
            {"@type": "Article", "url": QUEENS_AWARDS_URL},
        ],
        "knowsAbout": [
            "Medical artificial intelligence",
            "Medical image segmentation",
            "Foundation models",
            "Vision transformers",
            "Multimodal machine learning",
            "Clinical prediction",
        ],
    }
    profile_page = {
        "@type": "ProfilePage",
        "@id": f"{canonical}#page",
        "url": canonical,
        "name": "About Ramtin Mojtahedi",
        "description": "Source-backed professional biography, research identity, education, and profiles for Dr. Ramtin Mojtahedi.",
        "dateModified": modified,
        "inLanguage": "en-CA",
        "mainEntity": {"@id": PERSON_ID},
        "primaryImageOfPage": {"@type": "ImageObject", "url": PROFILE_IMAGE_URL},
    }
    schema = {
        "@context": "https://schema.org",
        "@graph": [
            person,
            profile_page,
            breadcrumb_schema([("Home", f"{BASE_URL}/"), ("About", canonical)]),
        ],
    }
    return f'''{GENERATED_MARKER}
<!doctype html>
<html lang="en-CA">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>About Dr. Ramtin Mojtahedi | Medical AI Researcher</title>
  <meta name="description" content="Source-backed biography of Dr. Ramtin Mojtahedi, a UHN postdoctoral researcher with a Queen's Ph.D. in Computing and a medical AI research portfolio.">
  <meta name="author" content="Dr. Ramtin Mojtahedi">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
  <link rel="canonical" href="{canonical}">
  <link rel="author" href="{ORCID_URL}">
  <link rel="alternate" type="application/atom+xml" title="Ramtin Mojtahedi publications" href="{BASE_URL}/publications.atom.xml">
  <link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="/assets/search-pages.css?v=20260802-3">
  <meta property="og:type" content="profile">
  <meta property="og:site_name" content="Ramtin Mojtahedi">
  <meta property="og:url" content="{canonical}">
  <meta property="og:title" content="About Dr. Ramtin Mojtahedi">
  <meta property="og:description" content="Professional biography, research identity, education, and authoritative profiles.">
  <meta property="og:image" content="{SOCIAL_IMAGE_URL}">
  <meta property="og:image:alt" content="Portrait of Dr. Ramtin Mojtahedi">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="About Dr. Ramtin Mojtahedi">
  <meta name="twitter:description" content="Professional biography, research identity, education, and authoritative profiles.">
  <meta name="twitter:image" content="{SOCIAL_IMAGE_URL}">
  {json_script(schema)}
</head>
<body>
  <a class="skip-link" href="#main-content">Skip to biography</a>
  {site_header(label="Biography navigation")}
  <main id="main-content">
    <article class="profile-article">
      <nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><span>About</span></nav>
      <div class="profile-intro">
        <div>
          <p class="eyebrow">Professional biography</p>
          <h1>Ramtin Mojtahedi</h1>
          <p class="lede">Postdoctoral medical AI researcher working across medical imaging, data-efficient learning, and multimodal clinical prediction.</p>
        </div>
        <img src="/assets/ramtin-graduation.svg" width="240" height="351" alt="Dr. Ramtin Mojtahedi in Queen’s University doctoral regalia holding his diploma">
      </div>

      <section aria-labelledby="biography-heading">
        <h2 id="biography-heading">Biography</h2>
        <p><strong>Ramtin Mojtahedi</strong> is listed as a postdoctoral researcher with the Sage Lab at University Health Network (UHN). His research portfolio focuses on medical artificial intelligence, including medical image segmentation, foundation models, vision transformers, representation learning, radiomics, and multimodal clinical prediction.</p>
        <p>Queen’s University’s official Spring 2026 convocation program records his Doctor of Philosophy in <strong>Computing</strong>, conferred at the June 24, 2026 ceremony under the formal name <strong>Ramtin Mojtahedi Saffari</strong>, with Amber Simpson listed as supervisor. His Queen’s lab profile documents earlier training in electrical and computer engineering and doctoral research on deep-learning methods for image-segmentation tasks.</p>
        <p>Queen’s School of Computing has also documented his 2024 recognition for graduate leadership, community engagement, student support, and contributions to the School’s intellectual and social community.</p>
      </section>

      <section id="publication-names" aria-labelledby="names-heading">
        <h2 id="names-heading">Name and publication identity</h2>
        <p>Current scholarly work is published as <strong>Ramtin Mojtahedi</strong>. Earlier engineering publications also appear under <strong>Ramtin Mojtahedi Saffari</strong> and <strong>R. M. Saffari</strong>. The persistent scholarly identifier is <a href="{ORCID_URL}" rel="me">ORCID 0000-0002-3953-3256</a>.</p>
      </section>

      <section aria-labelledby="profiles-heading">
        <h2 id="profiles-heading">Authoritative profiles and records</h2>
        <ul class="source-list">
          <li><a href="{SAGE_LAB_URL}">Sage Lab at UHN team profile</a> — current postdoctoral role.</li>
          <li><a href="{QUEENS_CONVOCATION_URL}">Queen’s University Spring 2026 convocation program</a> — degree, field, ceremony, formal name, and supervisor.</li>
          <li><a href="{SIMPSON_LAB_URL}">Simpson Lab profile at Queen’s University</a> — prior education and doctoral research focus.</li>
          <li><a href="{QUEENS_AWARDS_URL}">Queen’s School of Computing recognition</a> — documented 2024 awards and community contributions.</li>
          <li><a href="{ORCID_URL}" rel="me">ORCID record</a> and <a href="{GOOGLE_SCHOLAR_URL}">Google Scholar profile</a> — scholarly identity and publication discovery.</li>
        </ul>
      </section>

      <div class="actions"><a class="button primary" href="/publications/">View publications</a><a class="button secondary" href="/research/">Explore research themes</a></div>
      <p class="accuracy-note">This page separates independently verifiable facts from research descriptions supplied by the portfolio owner. It intentionally omits private or unsupported biographical details.</p>
    </article>
  </main>
  <footer>Biography and sources checked {esc(modified)} · <a href="/">Return to the portfolio</a></footer>
</body>
</html>
'''


def research_groups(
    publications: list[dict[str, object]],
) -> list[tuple[str, str, list[dict[str, object]]]]:
    clinical_terms = {
        "radiomic", "radiomics", "risk", "response", "therapy", "chemotherapy",
        "clinical", "multimodal", "cardiovascular", "slice thickness", "pancreatic",
        "survival prediction",
    }
    clinical: list[dict[str, object]] = []
    imaging: list[dict[str, object]] = []
    engineering: list[dict[str, object]] = []
    for publication in publications:
        searchable = " ".join(
            [
                str(publication.get("title") or ""),
                *(str(value) for value in publication.get("keywords") or []),
            ]
        ).casefold()
        if int(publication["year"]) <= 2017:
            engineering.append(publication)
        elif any(term in searchable for term in clinical_terms):
            clinical.append(publication)
        else:
            imaging.append(publication)
    return [
        (
            "Medical image segmentation and data-efficient learning",
            "Work on tumour segmentation and classification using vision transformers, self-supervised and contrastive learning, few-shot learning, persistent homology, and parameter-efficient adaptation of foundation models.",
            imaging,
        ),
        (
            "Multimodal clinical prediction and radiomics",
            "Research records connecting CT imaging, radiomic features, clinical variables, and machine-learning models for risk stratification, treatment response, and outcome prediction.",
            clinical,
        ),
        (
            "Engineering foundations",
            "Earlier work in signal processing, FPGA-based tracking, image encryption, Bayesian filtering, and sensor systems that forms part of the broader technical record.",
            engineering,
        ),
    ]


def research_page(publications: list[dict[str, object]]) -> str:
    canonical = f"{BASE_URL}/research/"
    groups = research_groups(publications)
    sections: list[str] = []
    item_list: list[dict[str, object]] = []
    position = 1
    for index, (heading, description, records) in enumerate(groups, start=1):
        cards = []
        for publication in records:
            cards.append(
                f'''<li class="research-paper">
  <span>{int(publication['year'])}</span>
  <a href="/publications/{esc(publication['id'], attribute=True)}/">{esc(publication['title'])}</a>
  <small>{esc(publication.get('venue'))}</small>
</li>'''
            )
            item_list.append(
                {
                    "@type": "ListItem",
                    "position": position,
                    "url": publication_url(publication),
                    "name": str(publication["title"]),
                }
            )
            position += 1
        sections.append(
            f'''<section class="theme" aria-labelledby="theme-{index}">
  <p class="theme-number">0{index}</p>
  <h2 id="theme-{index}">{esc(heading)}</h2>
  <p>{esc(description)}</p>
  <ul role="list">{''.join(cards)}</ul>
</section>'''
        )
    schema = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "CollectionPage",
                "@id": f"{canonical}#page",
                "url": canonical,
                "name": "Medical AI research themes by Ramtin Mojtahedi",
                "description": "Research themes and linked scholarly records in medical imaging AI, multimodal prediction, radiomics, and engineering.",
                "about": {"@id": PERSON_ID},
                "mainEntity": {
                    "@type": "ItemList",
                    "numberOfItems": len(item_list),
                    "itemListElement": item_list,
                },
                "inLanguage": "en-CA",
            },
            breadcrumb_schema([("Home", f"{BASE_URL}/"), ("Research", canonical)]),
        ],
    }
    return f'''{GENERATED_MARKER}
<!doctype html>
<html lang="en-CA">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Medical AI Research | Dr. Ramtin Mojtahedi</title>
  <meta name="description" content="Explore Ramtin Mojtahedi's medical AI research in image segmentation, foundation models, multimodal clinical prediction, radiomics, and engineering.">
  <meta name="author" content="Dr. Ramtin Mojtahedi">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
  <link rel="canonical" href="{canonical}">
  <link rel="author" href="{ORCID_URL}">
  <link rel="alternate" type="application/atom+xml" title="Ramtin Mojtahedi publications" href="{BASE_URL}/publications.atom.xml">
  <link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="/assets/search-pages.css?v=20260802-3">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Ramtin Mojtahedi">
  <meta property="og:url" content="{canonical}">
  <meta property="og:title" content="Medical AI Research | Dr. Ramtin Mojtahedi">
  <meta property="og:description" content="Research themes and linked scholarly records in medical imaging AI, multimodal prediction, radiomics, and engineering.">
  <meta property="og:image" content="{SOCIAL_IMAGE_URL}">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="Medical AI Research | Dr. Ramtin Mojtahedi">
  <meta name="twitter:description" content="Research themes and linked scholarly records in medical imaging AI, multimodal prediction, radiomics, and engineering.">
  <meta name="twitter:image" content="{SOCIAL_IMAGE_URL}">
  {json_script(schema)}
</head>
<body>
  <a class="skip-link" href="#main-content">Skip to research themes</a>
  {site_header(label="Research navigation")}
  <main id="main-content">
    <article class="research-hub">
      <nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><span>Research</span></nav>
      <p class="eyebrow">Research themes</p>
      <h1>Medical AI research grounded in clinical questions.</h1>
      <p class="lede">A thematic guide to {len(publications)} scholarly records, connecting medical image analysis, data-efficient learning, clinical prediction, radiomics, and earlier engineering work.</p>
      <div class="theme-grid">{''.join(sections)}</div>
      <aside class="scope-note"><h2>Scope and evidence</h2><p>These descriptions summarize the documented scope of the linked records. Publisher or source pages remain authoritative for full methods, results, limitations, and publication status.</p></aside>
    </article>
  </main>
  <footer><a href="/publications/">Browse the complete publication index</a> · <a href="/about/">About Ramtin Mojtahedi</a></footer>
</body>
</html>
'''


def atom_feed(publications: list[dict[str, object]]) -> str:
    updated = publication_feed_updated_at(publications)
    entries: list[str] = []
    for publication in publications:
        canonical = publication_url(publication)
        external_url = str(publication.get("url") or "").strip()
        published = str(publication["publication_date"])
        published_element = (
            ""
            if re.fullmatch(r"\d{4}", published)
            else f"\n    <published>{esc(published)}T00:00:00Z</published>"
        )
        alternate_link = (
            f'\n    <link rel="related" href="{esc(external_url, attribute=True)}" />'
            if external_url
            else ""
        )
        entries.append(
            f'''  <entry>
    <title>{esc(publication['title'])}</title>
    <id>{canonical}</id>
    <link rel="alternate" href="{canonical}" />{alternate_link}{published_element}
    <updated>{updated}</updated>
    <author><name>Ramtin Mojtahedi</name><uri>{ORCID_URL}</uri></author>
    <summary>{esc(plain_text(publication.get('citation_plain') or publication.get('citation', '')))}</summary>
  </entry>'''
        )
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>Ramtin Mojtahedi — Publications</title>
  <id>{BASE_URL}/publications/</id>
  <link rel="self" href="{BASE_URL}/publications.atom.xml" />
  <link rel="alternate" href="{BASE_URL}/publications/" />
  <updated>{updated}</updated>
  <author><name>Ramtin Mojtahedi</name><uri>{ORCID_URL}</uri></author>
{chr(10).join(entries)}
</feed>
'''


def publications_export(publications: list[dict[str, object]]) -> str:
    payload = {
        "schema_version": 1,
        "profile": {
            "name": "Ramtin Mojtahedi",
            "orcid": ORCID_URL,
            "google_scholar": GOOGLE_SCHOLAR_URL,
            "website": f"{BASE_URL}/",
        },
        "updated_at": publication_feed_updated_at(publications),
        "publication_count": len(publications),
        "publications": publications,
    }
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def bibtex_export(publications: list[dict[str, object]]) -> str:
    return "\n\n".join(bibtex_entry(publication) for publication in publications) + "\n"


def scholarly_pages_manifest(publications: list[dict[str, object]]) -> str:
    payload = {
        "schema_version": 1,
        "generated_at": latest_verified(publications),
        "count": len(publications),
        "pages": [publication_path(publication) for publication in publications],
        "record_exports": [
            {
                "id": publication["id"],
                "page": publication_path(publication),
                "bibtex": f"{publication_path(publication)}citation.bib",
                "ris": f"{publication_path(publication)}citation.ris",
                "json": f"{publication_path(publication)}metadata.json",
            }
            for publication in publications
        ],
        "exports": {
            "json": "/publications.json",
            "bibtex": "/publications.bib",
            "atom": "/publications.atom.xml",
        },
    }
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"

def search_urls(publications: list[dict[str, object]]) -> list[str]:
    return [
        f"{BASE_URL}/",
        f"{BASE_URL}/about/",
        f"{BASE_URL}/research/",
        f"{BASE_URL}/publications/",
        f"{BASE_URL}/publications.json",
        f"{BASE_URL}/publications.bib",
        f"{BASE_URL}/publications.atom.xml",
        f"{BASE_URL}/scholarly-pages.json",
        *(publication_url(publication) for publication in publications),
    ]


def sitemap(publications: list[dict[str, object]]) -> str:
    nodes = "\n".join(
        f"  <url>\n    <loc>{esc(url)}</loc>\n  </url>"
        for url in search_urls(publications)
        if url != f"{BASE_URL}/"
    )
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  <url>
    <loc>{BASE_URL}/</loc>
    <image:image>
      <image:loc>{PROFILE_IMAGE_URL}</image:loc>
      <image:title>Ramtin Mojtahedi at Queen's University convocation</image:title>
      <image:caption>Dr. Ramtin Mojtahedi in Queen's University doctoral regalia holding his diploma</image:caption>
    </image:image>
  </url>
{nodes}
</urlset>
'''


def indexnow_manifest(publications: list[dict[str, object]]) -> str:
    payload = {
        "host": "ramtin-mojtahedi.github.io",
        "key": INDEXNOW_KEY,
        "keyLocation": f"{BASE_URL}/{INDEXNOW_KEY}.txt",
        "urlList": search_urls(publications),
    }
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def expected_files(publications: list[dict[str, object]]) -> dict[Path, str]:
    files = {
        ABOUT_DIR / "index.html": about_page(publications),
        RESEARCH_DIR / "index.html": research_page(publications),
        PUBLICATIONS_DIR / "index.html": publications_index(publications),
        PUBLICATIONS_EXPORT_FILE: publications_export(publications),
        BIBTEX_FILE: bibtex_export(publications),
        ATOM_FILE: atom_feed(publications),
        SCHOLARLY_PAGES_FILE: scholarly_pages_manifest(publications),
        SITEMAP_FILE: sitemap(publications),
        INDEXNOW_FILE: indexnow_manifest(publications),
    }
    for publication in publications:
        publication_dir = PUBLICATIONS_DIR / str(publication["id"])
        files[publication_dir / "index.html"] = publication_page(publication, publications)
        files[publication_dir / "citation.bib"] = bibtex_entry(publication) + "\n"
        files[publication_dir / "citation.ris"] = ris_entry(publication)
        files[publication_dir / "metadata.json"] = publication_metadata_export(
            publication, publications
        )
    return files

def validate(publications: list[dict[str, object]]) -> None:
    if not isinstance(publications, list) or not publications:
        raise RuntimeError("No publication records found.")
    ids = [str(publication.get("id") or "") for publication in publications]
    if len(ids) != len(set(ids)) or any(not re.fullmatch(r"[a-z0-9-]+", value) for value in ids):
        raise RuntimeError("Publication ids must be unique URL-safe slugs.")
    bibtex_keys = [bibtex_key(publication) for publication in publications]
    if len(bibtex_keys) != len(set(bibtex_keys)) or any(
        not re.fullmatch(r"[A-Za-z0-9:._-]+", value) for value in bibtex_keys
    ):
        raise RuntimeError("BibTeX keys must be unique and citation-safe.")
    dois = [str(publication.get("doi") or "").strip().lower() for publication in publications]
    dois = [value for value in dois if value]
    if len(dois) != len(set(dois)):
        raise RuntimeError("Publication DOIs must be unique.")
    if not INDEXNOW_KEY_FILE.is_file() or INDEXNOW_KEY_FILE.read_text(encoding="utf-8").strip() != INDEXNOW_KEY:
        raise RuntimeError("The IndexNow key file is missing or does not match the manifest key.")
    for publication in publications:
        missing = [
            field
            for field in ("id", "title", "year", "publication_date", "authors_html", "citation", "status")
            if not publication.get(field)
        ]
        if missing:
            raise RuntimeError(f"{publication.get('id', '<unknown>')}: missing {', '.join(missing)}")
        date = str(publication["publication_date"])
        if not re.fullmatch(r"\d{4}(?:-\d{2}-\d{2})?", date):
            raise RuntimeError(f"{publication['id']}: publication date must be a verified year or ISO date")
        if abs(int(date[:4]) - int(publication["year"])) > 1:
            raise RuntimeError(f"{publication['id']}: publication date is inconsistent with the conference year")
        if not author_names(publication):
            raise RuntimeError(f"{publication['id']}: no authors could be parsed")
        expected_detail_url = publication_path(publication)
        detail_url = str(publication.get("detail_url") or expected_detail_url)
        if detail_url != expected_detail_url:
            raise RuntimeError(f"{publication['id']}: detail_url does not match its canonical slug")
        for field in (
            "url",
            "open_access_url",
            "preprint_url",
            "code_url",
            "pubmed_url",
            "pmc_url",
            "institutional_url",
            "bibliography_url",
            "citation_pdf_url",
            "manuscript_terms_url",
            "open_access_license_url",
        ):
            value = str(publication.get(field) or "").strip()
            if value and not value.startswith("https://"):
                raise RuntimeError(f"{publication['id']}: {field} must use HTTPS")
        citation_pdf_url = str(publication.get("citation_pdf_url") or "").strip()
        if citation_pdf_url.startswith(f"{BASE_URL}/"):
            if not citation_pdf_url.startswith(f"{BASE_URL}{expected_detail_url}"):
                raise RuntimeError(
                    f"{publication['id']}: citation_pdf_url must be in the publication page directory"
                )
            if not publication.get("sharing_notice") or not publication.get("manuscript_terms_url"):
                raise RuntimeError(
                    f"{publication['id']}: hosted manuscripts require a version notice and publisher terms"
                )
            local_pdf = ROOT / unquote(urlparse(citation_pdf_url).path).lstrip("/")
            if not local_pdf.is_file():
                raise RuntimeError(
                    f"{publication['id']}: citation_pdf_url does not resolve to a local file"
                )

def unexpected_pages(files: dict[Path, str]) -> list[Path]:
    return sorted(path for path in PUBLICATIONS_DIR.glob("*/index.html") if path not in files)


def prune_orphans(files: dict[Path, str]) -> None:
    for path in unexpected_pages(files):
        content = path.read_text(encoding="utf-8")
        siblings = list(path.parent.iterdir())
        generated_names = {"index.html", "citation.bib", "citation.ris", "metadata.json"}
        if GENERATED_MARKER not in content or any(sibling.name not in generated_names for sibling in siblings):
            raise RuntimeError(f"Refusing to remove non-generated publication content: {path.relative_to(ROOT)}")
        for sibling in siblings:
            sibling.unlink()
        path.parent.rmdir()
        print(f"Removed obsolete generated page: {path.relative_to(ROOT)}")

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are missing or stale")
    args = parser.parse_args()

    publications = json.loads(PUBLICATIONS_FILE.read_text(encoding="utf-8"))
    validate(publications)
    files = expected_files(publications)

    if args.check:
        stale = [
            str(path.relative_to(ROOT))
            for path, content in files.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            print("Stale or missing generated search files:", file=sys.stderr)
            print("\n".join(f"- {path}" for path in stale), file=sys.stderr)
            return 1
        unexpected = [str(path.relative_to(ROOT)) for path in unexpected_pages(files)]
        if unexpected:
            print("Unexpected generated publication pages:", file=sys.stderr)
            print("\n".join(f"- {path}" for path in unexpected), file=sys.stderr)
            return 1
        print(
            f"Verified {len(publications)} publication pages, identity and research pages, "
            "citation exports, Atom feed, sitemap, and IndexNow manifest."
        )
        return 0

    prune_orphans(files)
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    print(
        f"Built {len(publications)} publication pages, identity and research pages, "
        "citation exports, publications.atom.xml, sitemap.xml, and indexnow.json."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
