#!/usr/bin/env python3
"""Validate the complete portfolio source before GitHub Pages publishes it."""

from __future__ import annotations

import datetime as dt
import json
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PUBLIC_EMAIL = "Ramtin.Mojtahedi@utoronto.ca"
PRIVATE_RECIPIENT = "MojtahediRamtin@gmail.com"
MINIMUM_PUBLICATIONS = 18
SUCCESS_MESSAGE = "Thanks for your message. We will contact you shortly. Thanks!"

FILES = {
    "index": ROOT / "index.html",
    "hero": ROOT / "_includes/site-part-1.html",
    "publications_section": ROOT / "_includes/site-part-2.html",
    "activity": ROOT / "_includes/site-part-3.html",
    "contact": ROOT / "_includes/site-part-4.html",
    "contact_js": ROOT / "assets/contact-form.js",
    "contact_css": ROOT / "assets/contact-form-polish.css",
    "publications_css": ROOT / "assets/publications.css",
    "publications": ROOT / "_data/publications.json",
    "metrics": ROOT / "_data/site_metrics.json",
    "maintenance": ROOT / "_data/site_maintenance.json",
    "sitemap": ROOT / "sitemap.xml",
}

EXPECTED_CATEGORIES = {
    "Research collaboration",
    "Clinical or medical AI collaboration",
    "Speaking, seminar, or panel invitation",
    "Academic reviewing or editorial service",
    "Student, mentorship, or supervision inquiry",
    "Open-source or technical question",
    "Consulting or professional opportunity",
    "Media or interview request",
    "Other professional inquiry",
}

REQUIRED_IDS = {
    "main", "home", "expertise", "profile", "experience", "publications",
    "presentations", "recognition", "teaching", "service", "code", "contact",
}

FORBIDDEN_PUBLIC_MARKERS = {
    "automatic scholarly update",
    "automatically maintained",
    "new verified records are added without deleting the cv baseline",
    "open google scholar ↗",
    "publication-sync-note",
    "maintenance-status",
    "site-status.json",
    "publication-auto.css",
    "site-maintenance.css",
    "ai-generated",
    "generated by ai",
    "created by ai",
    "written by ai",
    "powered by ai",
    "chatgpt-generated",
}

STAT_LABELS = {
    "publication_count": "Peer-reviewed, accepted, and published works",
    "presentation_count": "Oral and poster presentations",
    "recognition_count": "Honours, awards, and distinctions",
    "reviewer_venue_count": "Reviewer and service venues",
    "leadership_role_count": "Leadership and volunteer roles",
}


def fail(message: str) -> None:
    raise AssertionError(message)


def read(path: Path) -> str:
    if not path.is_file():
        fail(f"Required file is missing: {path.relative_to(ROOT)}")
    return path.read_text(encoding="utf-8")


def read_json(path: Path):
    return json.loads(read(path))


def count(pattern: str, source: str) -> int:
    return len(re.findall(pattern, source, flags=re.IGNORECASE | re.DOTALL))


def reviewer_count(service: str) -> int:
    match = re.search(
        r'<h3>Reviewer and professional service</h3>\s*<ul class="clean">(.*?)</ul>',
        service,
        flags=re.IGNORECASE | re.DOTALL,
    )
    if not match:
        fail("Reviewer-service list is missing.")
    return count(r"<li(?:\s|>)", match.group(1))


def stat_value(hero: str, label: str) -> int:
    match = re.search(
        rf"<div class='stat'>\s*<b[^>]*data-count='(\d+)'[^>]*>[^<]*</b>\s*"
        rf"<span>{re.escape(label)}</span>\s*</div>",
        hero,
    )
    if not match:
        fail(f"Statistic is missing: {label}")
    return int(match.group(1))


def validate_publications() -> tuple[list[dict], dict]:
    publications = read_json(FILES["publications"])
    metrics = read_json(FILES["metrics"])
    if not isinstance(publications, list) or len(publications) < MINIMUM_PUBLICATIONS:
        fail("The curated publication baseline is incomplete.")

    titles = [str(item.get("title") or "").strip() for item in publications]
    if any(not title for title in titles) or len({title.casefold() for title in titles}) != len(titles):
        fail("Publication titles are missing or duplicated.")
    if int(metrics.get("publication_count", -1)) != len(publications):
        fail("Publication count and publication data differ.")
    if any(not isinstance(item.get("year"), int) or not 1900 <= item["year"] <= 2100 for item in publications):
        fail("A publication year is invalid.")
    if any("Automated scholarly source" in str(item.get("source") or "") for item in publications):
        fail("A legacy publication-source label remains.")
    return publications, metrics


def validate_counts(hero: str, activity: str, service: str, metrics: dict) -> dict[str, int]:
    counters = re.findall(r"data-count=(?:'|\")([^'\"]+)(?:'|\")", hero)
    if not counters or any(not re.fullmatch(r"\d+", value) for value in counters):
        fail("A public statistic is missing or non-numeric.")
    if "NaN" in hero or "\x88" in hero:
        fail("An invalid-number artifact remains.")

    oral = count(r"<small>Oral\s*·", activity)
    poster = count(r"<small>Poster\s*·", activity)
    expected = {
        "publication_count": int(metrics.get("publication_count", 0)),
        "presentation_count": oral + poster,
        "oral_presentation_count": oral,
        "poster_presentation_count": poster,
        "recognition_count": count(r"<article class='award[^']*'>", activity),
        "teaching_topic_count": count(r"<article class='teach[^']*'>", activity),
        "reviewer_venue_count": reviewer_count(service),
        "leadership_role_count": count(r'<article class="lead[^\"]*">', service),
    }
    if any(value < 1 for value in expected.values()):
        fail(f"One or more public sections are empty: {expected}")

    for key, label in STAT_LABELS.items():
        if stat_value(hero, label) != expected[key]:
            fail(f"Public statistic is out of sync: {label}")
    for key, value in expected.items():
        if int(metrics.get(key, -1)) != value:
            fail(f"Site metric is out of sync: {key}")

    if f"{oral} oral and {poster} poster presentations." not in activity:
        fail("Presentation heading is out of sync.")
    if f"{expected['recognition_count']} honours, awards, grants, and distinctions." not in activity:
        fail("Recognition heading is out of sync.")
    if f"Show all {expected['recognition_count']} distinctions ↓" not in activity:
        fail("Recognition button is out of sync.")
    return expected


def validate_structure(index: str, parts: str) -> None:
    source = index + "\n" + parts
    ids = re.findall(r"\bid=(?:'|\")([^'\"]+)(?:'|\")", source)
    duplicates = sorted(value for value, total in Counter(ids).items() if total > 1)
    if duplicates:
        fail(f"Duplicate HTML ids: {duplicates}")
    missing = sorted(REQUIRED_IDS - set(ids))
    if missing:
        fail(f"Required public sections are missing: {missing}")
    targets = set(re.findall(r"href=(?:'|\")#([^'\"]+)(?:'|\")", source))
    broken = sorted(targets - set(ids))
    if broken:
        fail(f"Broken internal links: {broken}")
    external = re.findall(r"<a\b[^>]*target=(?:'|\")_blank(?:'|\")[^>]*>", source)
    if any("noopener" not in tag for tag in external):
        fail("Every new-window link must use rel=noopener.")


def validate_public_copy(index: str, parts: str) -> None:
    source = (index + "\n" + parts).casefold()
    found = sorted(marker for marker in FORBIDDEN_PUBLIC_MARKERS if marker in source)
    if found:
        fail(f"Visitor-facing implementation markers remain: {found}")
    if "assets/publications.css" not in index or not FILES["publications_css"].is_file():
        fail("The publications stylesheet is not connected.")
    if (ROOT / "assets/publication-auto.css").exists() or (ROOT / "assets/site-maintenance.css").exists():
        fail("Legacy visible-maintenance stylesheets remain.")


def validate_contact(index: str, contact: str, script: str, style: str) -> None:
    if PUBLIC_EMAIL not in contact or f"mailto:{PUBLIC_EMAIL}" not in contact:
        fail("The public contact email is missing.")
    mailtos = {
        value.lower()
        for value in re.findall(r"mailto:([^\"'<>\s]+)", index + "\n" + contact, flags=re.I)
    }
    if mailtos != {PUBLIC_EMAIL.lower()}:
        fail(f"Unexpected visible mailto addresses: {sorted(mailtos)}")
    if not all(f"'{piece}'" in script for piece in ("Mojtahedi", "Ramtin", "@gmail.com")):
        fail("The private form recipient is not assembled correctly.")
    if PRIVATE_RECIPIENT.lower() in (index + contact).lower() or "Ramtn" in script:
        fail("Private or misspelled recipient data is visible.")
    if "Please do not include patient-identifiable" in index + contact:
        fail("The removed contact disclaimer remains.")
    if re.search(r"\b(?:minlength|maxlength)\s*=", contact, flags=re.I):
        fail("The contact form has a character limit.")
    if "messageCount" in contact + script or ".slice(0," in script:
        fail("Legacy contact truncation remains.")

    options = {value for value in re.findall(r'<option\s+value="([^"]*)"', contact) if value}
    if options != EXPECTED_CATEGORIES:
        fail("Contact inquiry categories differ from the approved set.")
    if any(repr(category) not in script for category in EXPECTED_CATEGORIES):
        fail("Contact JavaScript is missing an approved category.")
    required = ("inquiry_type", "reply_to", "hp_email", "rateLimitStorageKey", "minimumCompletionMs", SUCCESS_MESSAGE)
    if any(token not in script for token in required):
        fail("Contact JavaScript is missing a delivery safeguard.")
    if "contact-form-polish.css" not in index or "contact-form.js" not in index:
        fail("Contact assets are not connected.")
    if ".contact .field select" not in style:
        fail("The contact-category control lacks dedicated styling.")


def validate_maintenance(publication_count: int, metrics: dict) -> None:
    maintenance = read_json(FILES["maintenance"])
    sitemap = read(FILES["sitemap"])
    if maintenance.get("status") != "current" or int(maintenance.get("publication_count", -1)) != publication_count:
        fail("Internal maintenance data is inconsistent.")
    try:
        dt.date.fromisoformat(str(maintenance.get("last_checked", "")))
    except ValueError as error:
        fail(f"Internal maintenance date is invalid: {error}")
    if maintenance.get("frequency") != "daily" or maintenance.get("schedule_display") != "Every day":
        fail("Maintenance is not configured for every day.")
    if len(maintenance.get("checks") or []) < 6:
        fail("The daily maintenance scope is incomplete.")
    if metrics.get("maintenance_frequency") != "daily" or "checked daily" not in str(metrics.get("publication_source_note") or "").lower():
        fail("Daily maintenance metadata is inconsistent.")
    if (ROOT / "site-status.json").exists() or "site-status.json" in sitemap:
        fail("The obsolete public status endpoint remains.")
    for url in ("https://ramtin-mojtahedi.github.io/", "https://ramtin-mojtahedi.github.io/publications.json"):
        if url not in sitemap:
            fail(f"Sitemap entry is missing: {url}")
    frequencies = re.findall(r"<changefreq>([^<]+)</changefreq>", sitemap)
    if not frequencies or any(value != "daily" for value in frequencies):
        fail("Every sitemap entry must use daily frequency.")


def main() -> int:
    sources = {name: read(path) for name, path in FILES.items() if name not in {"publications", "metrics", "maintenance"}}
    parts = "\n".join(sources[name] for name in ("hero", "publications_section", "activity", "contact"))
    publications, metrics = validate_publications()
    counts = validate_counts(sources["hero"], sources["activity"], sources["contact"], metrics)
    validate_structure(sources["index"], parts)
    validate_public_copy(sources["index"], parts)
    validate_contact(sources["index"], sources["contact"], sources["contact_js"], sources["contact_css"])
    validate_maintenance(len(publications), metrics)

    print("Website validation passed.")
    print(f"- Public sections: {len(REQUIRED_IDS) - 1}")
    print(f"- Publications: {len(publications)}")
    print(f"- Presentations: {counts['presentation_count']}")
    print(f"- Recognition entries: {counts['recognition_count']}")
    print(f"- Leadership roles: {counts['leadership_role_count']}")
    print("- Visitor-facing implementation markers: none")
    print("- Maintenance schedule: daily")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (AssertionError, json.JSONDecodeError) as error:
        print(f"Website validation failed: {error}", file=sys.stderr)
        raise SystemExit(1)
