#!/usr/bin/env python3
"""Validate the complete portfolio source before GitHub Pages publishes it."""

from __future__ import annotations

import datetime as dt
import json
import re
import sys
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PUBLIC_EMAIL = "Ramtin.Mojtahedi@utoronto.ca"
MINIMUM_PUBLICATIONS = 18
REQUIRED_PUBLICATION_IDS = {"self-supervised-transformer-liver-tumor-2026"}
EXCLUDED_UNVERIFIED_IDS = {"doctoral-dissertation-liver-cancer-2025"}
SUCCESS_MESSAGE = "Thanks for your message. We will contact you shortly. Thanks!"

FILES = {
    "index": ROOT / "index.html",
    "hero": ROOT / "_includes/site-part-1.html",
    "publications_section": ROOT / "_includes/site-part-2.html",
    "activity": ROOT / "_includes/site-part-3.html",
    "contact": ROOT / "_includes/site-part-4.html",
    "contact_js": ROOT / "assets/contact-form.js",
    "contact_css": ROOT / "assets/contact-form-polish.css",
    "publications_css": ROOT / "assets/publications.css",
    "publications": ROOT / "_data/publications.json",
    "publication_feed": ROOT / "publications.json",
    "publication_bibtex": ROOT / "publications.bib",
    "publication_atom": ROOT / "publications.atom.xml",
    "scholarly_pages": ROOT / "scholarly-pages.json",
    "metrics": ROOT / "_data/site_metrics.json",
    "maintenance": ROOT / "_data/site_maintenance.json",
    "about": ROOT / "about/index.html",
    "research": ROOT / "research/index.html",
    "citation": ROOT / "CITATION.cff",
    "sitemap": ROOT / "sitemap.xml",
    "robots": ROOT / "robots.txt",
    "indexnow": ROOT / "indexnow.json",
    "indexnow_key": ROOT / "898f0caec5d8b22a095db2a4afa88722.txt",
}

EXPECTED_CATEGORIES = {
    "Research collaboration",
    "Clinical or medical AI collaboration",
    "Speaking, seminar, or panel invitation",
    "Academic reviewing or editorial service",
    "Student, mentorship, or supervision inquiry",
    "Open-source or technical question",
    "Consulting or professional opportunity",
    "Media or interview request",
    "Other professional inquiry",
}

REQUIRED_IDS = {
    "main", "home", "expertise", "profile", "experience", "publications",
    "presentations", "recognition", "teaching", "service", "code", "contact",
}

FORBIDDEN_PUBLIC_MARKERS = {
    "automatic scholarly update",
    "automatically maintained",
    "new verified records are added without deleting the cv baseline",
    "open google scholar ↗",
    "publication-sync-note",
    "maintenance-status",
    "site-status.json",
    "publication-auto.css",
    "site-maintenance.css",
    "ai-generated",
    "generated by ai",
    "created by ai",
    "written by ai",
    "powered by ai",
    "chatgpt-generated",
}

NUMBER_WORDS = {
    0: "zero", 1: "one", 2: "two", 3: "three", 4: "four", 5: "five",
    6: "six", 7: "seven", 8: "eight", 9: "nine", 10: "ten",
    11: "eleven", 12: "twelve", 13: "thirteen", 14: "fourteen",
    15: "fifteen", 16: "sixteen", 17: "seventeen", 18: "eighteen",
    19: "nineteen", 20: "twenty",
}


def display_count(value: int) -> str:
    return NUMBER_WORDS.get(value, str(value))


STAT_LABELS = {
    "publication_count": "Publications and scholarly works",
    "presentation_count": "Oral and poster presentations",
    "recognition_count": "Honours, awards, and distinctions",
    "reviewer_venue_count": "Reviewer and service venues",
    "leadership_role_count": "Leadership and volunteer roles",
}


def fail(message: str) -> None:
    raise AssertionError(message)


def read(path: Path) -> str:
    if not path.is_file():
        fail(f"Required file is missing: {path.relative_to(ROOT)}")
    return path.read_text(encoding="utf-8")


def read_json(path: Path):
    return json.loads(read(path))


def count(pattern: str, source: str) -> int:
    return len(re.findall(pattern, source, flags=re.IGNORECASE | re.DOTALL))


def reviewer_count(service: str) -> int:
    match = re.search(
        r'<h3>Reviewer and professional service</h3>\s*<ul class="clean">(.*?)</ul>',
        service,
        flags=re.IGNORECASE | re.DOTALL,
    )
    if not match:
        fail("Reviewer-service list is missing.")
    return count(r"<li(?:\s|>)", match.group(1))


def stat_value(hero: str, label: str) -> int:
    match = re.search(
        rf"<div class='stat'>\s*<b[^>]*data-count='(\d+)'[^>]*>[^<]*</b>\s*"
        rf"<span>{re.escape(label)}</span>\s*</div>",
        hero,
    )
    if not match:
        fail(f"Statistic is missing: {label}")
    return int(match.group(1))


def validate_publications() -> tuple[list[dict], dict]:
    publications = read_json(FILES["publications"])
    metrics = read_json(FILES["metrics"])
    if not isinstance(publications, list) or len(publications) < MINIMUM_PUBLICATIONS:
        fail("The curated publication baseline is incomplete.")

    titles = [str(item.get("title") or "").strip() for item in publications]
    if any(not title for title in titles) or len({title.casefold() for title in titles}) != len(titles):
        fail("Publication titles are missing or duplicated.")
    publication_ids = {str(item.get("id") or "") for item in publications}
    missing_ids = sorted(REQUIRED_PUBLICATION_IDS - publication_ids)
    if missing_ids:
        fail(f"Required curated publication records are missing: {missing_ids}")
    unverified_ids = sorted(EXCLUDED_UNVERIFIED_IDS & publication_ids)
    if unverified_ids:
        fail(f"Unverified publication records must remain excluded: {unverified_ids}")
    if int(metrics.get("publication_count", -1)) != len(publications):
        fail("Publication count and publication data differ.")
    if any(not isinstance(item.get("peer_reviewed"), bool) for item in publications):
        fail("Every publication must explicitly identify its peer-review status.")
    peer_count = sum(item.get("peer_reviewed") is True for item in publications)
    submitted_count = sum(str(item.get("status") or "").strip().casefold() == "submitted" for item in publications)
    if int(metrics.get("peer_reviewed_or_accepted_count", -1)) != peer_count:
        fail("Peer-reviewed publication count and publication data differ.")
    if int(metrics.get("submitted_count", -1)) != submitted_count:
        fail("Submitted publication count and publication data differ.")
    if any(not isinstance(item.get("year"), int) or not 1900 <= item["year"] <= 2100 for item in publications):
        fail("A publication year is invalid.")
    if any("Automated scholarly source" in str(item.get("source") or "") for item in publications):
        fail("A legacy publication-source label remains.")
    for item in publications:
        bibliographic_text = " ".join(
            str(item.get(field) or "")
            for field in ("status", "venue", "citation", "citation_plain")
        )
        if re.search(r"(?:\s\?\s|\d\?\d)", bibliographic_text):
            fail(f"Publication punctuation appears corrupted: {item.get('id')}")
    return publications, metrics


def validate_counts(hero: str, activity: str, service: str, metrics: dict) -> dict[str, int]:
    counters = re.findall(r"data-count=(?:'|\")([^'\"]+)(?:'|\")", hero)
    if not counters or any(not re.fullmatch(r"\d+", value) for value in counters):
        fail("A public statistic is missing or non-numeric.")
    if "NaN" in hero or "\x88" in hero:
        fail("An invalid-number artifact remains.")

    oral = count(r"<small>Oral\s*·", activity)
    poster = count(r"<small>Poster\s*·", activity)
    expected = {
        "publication_count": int(metrics.get("publication_count", 0)),
        "presentation_count": oral + poster,
        "oral_presentation_count": oral,
        "poster_presentation_count": poster,
        "recognition_count": count(r"<article class='award[^']*'>", activity),
        "teaching_topic_count": count(r"<article class='teach[^']*'>", activity),
        "reviewer_venue_count": reviewer_count(service),
        "leadership_role_count": count(r'<article class="lead[^\"]*">', service),
    }
    if any(value < 1 for value in expected.values()):
        fail(f"One or more public sections are empty: {expected}")

    for key, label in STAT_LABELS.items():
        if stat_value(hero, label) != expected[key]:
            fail(f"Public statistic is out of sync: {label}")
    for key, value in expected.items():
        if int(metrics.get(key, -1)) != value:
            fail(f"Site metric is out of sync: {key}")

    presentation_heading = (
        f"{display_count(oral).capitalize()} oral and "
        f"{display_count(poster)} poster presentations."
    )
    if presentation_heading not in activity:
        fail("Presentation heading is out of sync.")
    if f"{expected['recognition_count']} honours, awards, grants, and distinctions." not in activity:
        fail("Recognition heading is out of sync.")
    if f"Show all {expected['recognition_count']} distinctions ↓" not in activity:
        fail("Recognition button is out of sync.")
    return expected


def validate_structure(index: str, parts: str) -> None:
    source = index + "\n" + parts
    ids = re.findall(r"\bid=(?:'|\")([^'\"]+)(?:'|\")", source)
    duplicates = sorted(value for value, total in Counter(ids).items() if total > 1)
    if duplicates:
        fail(f"Duplicate HTML ids: {duplicates}")
    missing = sorted(REQUIRED_IDS - set(ids))
    if missing:
        fail(f"Required public sections are missing: {missing}")
    targets = set(re.findall(r"href=(?:'|\")#([^'\"]+)(?:'|\")", source))
    broken = sorted(targets - set(ids))
    if broken:
        fail(f"Broken internal links: {broken}")
    external = re.findall(r"<a\b[^>]*target=(?:'|\")_blank(?:'|\")[^>]*>", source)
    if any("noopener" not in tag for tag in external):
        fail("Every new-window link must use rel=noopener.")


def validate_public_copy(index: str, parts: str) -> None:
    source = (index + "\n" + parts).casefold()
    found = sorted(marker for marker in FORBIDDEN_PUBLIC_MARKERS if marker in source)
    if found:
        fail(f"Visitor-facing implementation markers remain: {found}")
    if "assets/publications.css" not in index or not FILES["publications_css"].is_file():
        fail("The publications stylesheet is not connected.")
    if (ROOT / "assets/publication-auto.css").exists() or (ROOT / "assets/site-maintenance.css").exists():
        fail("Legacy visible-maintenance stylesheets remain.")


def validate_contact(index: str, contact: str, script: str, style: str) -> None:
    if PUBLIC_EMAIL not in contact or f"mailto:{PUBLIC_EMAIL}" not in contact:
        fail("The public contact email is missing.")
    mailtos = {
        value.lower()
        for value in re.findall(r"mailto:([^\"'<>\s]+)", index + "\n" + contact, flags=re.I)
    }
    if mailtos != {PUBLIC_EMAIL.lower()}:
        fail(f"Unexpected visible mailto addresses: {sorted(mailtos)}")
    if not all(f"'{piece}'" in script for piece in ("Mojtahedi", "Ramtin", "@gmail.com")):
        fail("The private form recipient is not assembled correctly.")
    if re.search(r"mailto:[^\"'<>\s]+@gmail\.com", index + contact, flags=re.I) or "Ramtn" in script:
        fail("Private or misspelled recipient data is visible.")
    if "Please do not include patient-identifiable" in index + contact:
        fail("The removed contact disclaimer remains.")
    if re.search(r"\b(?:minlength|maxlength)\s*=", contact, flags=re.I):
        fail("The contact form has a character limit.")
    if "messageCount" in contact + script or ".slice(0," in script:
        fail("Legacy contact truncation remains.")

    options = {value for value in re.findall(r'<option\s+value="([^"]*)"', contact) if value}
    if options != EXPECTED_CATEGORIES:
        fail("Contact inquiry categories differ from the approved set.")
    if any(repr(category) not in script for category in EXPECTED_CATEGORIES):
        fail("Contact JavaScript is missing an approved category.")
    required = ("inquiry_type", "reply_to", "hp_email", "rateLimitStorageKey", "minimumCompletionMs", SUCCESS_MESSAGE)
    if any(token not in script for token in required):
        fail("Contact JavaScript is missing a delivery safeguard.")
    if "contact-form-polish.css" not in index or "contact-form.js" not in index:
        fail("Contact assets are not connected.")
    if ".contact .field select" not in style:
        fail("The contact-category control lacks dedicated styling.")


def validate_scholarly_exports(publications: list[dict]) -> None:
    feed = read_json(FILES["publication_feed"])
    if not isinstance(feed, dict):
        fail("publications.json must be an object-format publication feed.")
    if feed.get("schema_version") != 1:
        fail("The publication feed schema version is invalid.")
    if int(feed.get("publication_count", -1)) != len(publications):
        fail("The publication feed count differs from the curated data.")
    if feed.get("publications") != publications:
        fail("The publication feed records differ from the curated data.")
    profile = feed.get("profile") or {}
    if profile.get("orcid") != "https://orcid.org/0000-0002-3953-3256" or not feed.get("updated_at"):
        fail("The publication feed profile or update timestamp is incomplete.")

    bibtex = read(FILES["publication_bibtex"])
    expected_keys = [str(publication.get("bibtex_key") or "") for publication in publications]
    if any(not key for key in expected_keys) or len(expected_keys) != len(set(expected_keys)):
        fail("Every curated publication must have a unique BibTeX key.")
    exported_keys = re.findall(r"(?m)^@[A-Za-z]+\{([^,\s]+),", bibtex)
    if exported_keys != expected_keys:
        fail("The complete BibTeX export differs from the curated publication order or keys.")

    atom = read(FILES["publication_atom"])
    try:
        atom_feed = ET.fromstring(atom)
    except ET.ParseError as error:
        fail(f"Publication Atom feed is invalid XML: {error}")
    namespace = {"atom": "http://www.w3.org/2005/Atom"}
    entries = atom_feed.findall("atom:entry", namespace)
    if len(entries) != len(publications):
        fail("Publication Atom feed entry count differs from the curated data.")
    if not all(entry.find("atom:link", namespace) is not None for entry in entries):
        fail("Publication Atom feed contains an entry without a canonical link.")
    for publication, entry in zip(publications, entries):
        publication_date = str(publication.get("publication_date") or "")
        published_element = entry.find("atom:published", namespace)
        if re.fullmatch(r"\d{4}", publication_date):
            if published_element is not None:
                fail(f"Atom feed invents an exact date for year-only record: {publication['id']}")
        elif published_element is None or published_element.text != f"{publication_date}T00:00:00Z":
            fail(f"Atom feed publication date is missing or incorrect: {publication['id']}")

    manifest = read_json(FILES["scholarly_pages"])
    expected_pages = [f"/publications/{publication['id']}/" for publication in publications]
    if manifest.get("schema_version") != 1 or int(manifest.get("count", -1)) != len(publications):
        fail("The scholarly-page manifest count or schema version is invalid.")
    if manifest.get("pages") != expected_pages:
        fail("The scholarly-page manifest differs from the curated publication pages.")
    if manifest.get("exports") != {
        "json": "/publications.json",
        "bibtex": "/publications.bib",
        "atom": "/publications.atom.xml",
    }:
        fail("The scholarly-page manifest does not advertise all citation exports.")


def validate_discovery_pages(sources: dict[str, str]) -> None:
    expected_pages = {
        "about": "https://ramtin-mojtahedi.github.io/about/",
        "research": "https://ramtin-mojtahedi.github.io/research/",
    }
    for name, canonical in expected_pages.items():
        page = sources[name]
        if f'<link rel="canonical" href="{canonical}">' not in page:
            fail(f"{name} page canonical URL is missing or incorrect.")
        if 'name="robots" content="index, follow' not in page:
            fail(f"{name} page is not explicitly indexable.")
        if 'application/ld+json' not in page or 'BreadcrumbList' not in page:
            fail(f"{name} page is missing structured discovery metadata.")

    inaccurate_degree_copy = (
        "Ph.D. completed in 2025",
        "Ph.D. in Medical AI",
        "Completed 2025",
    )
    if any(value in sources["hero"] for value in inaccurate_degree_copy):
        fail("The homepage contains a degree label or date that conflicts with the Queen's record.")
    required_identity_copy = (
        "Ph.D. in Computing conferred by Queen’s University in 2026",
        "Ramtin Mojtahedi Saffari",
        "R. M. Saffari",
        "href='/about/'",
        "href='/research/'",
    )
    if any(value not in sources["hero"] for value in required_identity_copy):
        fail("The homepage is missing corrected degree, name-identity, or discovery links.")

    required_citation_tokens = (
        "cff-version: 1.2.0",
        "orcid: https://orcid.org/0000-0002-3953-3256",
        "url: https://ramtin-mojtahedi.github.io/",
    )
    if any(token not in sources["citation"] for token in required_citation_tokens):
        fail("CITATION.cff is missing required identity metadata.")
    if '"name": "Ramtin Mojtahedi"' not in sources["index"]:
        fail("Homepage Person structured data does not use the canonical personal name.")
    if "<image:image>" not in sources["sitemap"]:
        fail("The sitemap does not advertise the portfolio's public images.")


def validate_maintenance(publications: list[dict], metrics: dict) -> None:
    maintenance = read_json(FILES["maintenance"])
    sitemap = read(FILES["sitemap"])
    publication_count = len(publications)
    if maintenance.get("status") != "current" or int(maintenance.get("publication_count", -1)) != publication_count:
        fail("Internal maintenance data is inconsistent.")
    try:
        dt.date.fromisoformat(str(maintenance.get("last_checked", "")))
    except ValueError as error:
        fail(f"Internal maintenance date is invalid: {error}")
    if maintenance.get("frequency") != "daily" or maintenance.get("schedule_display") != "Every day":
        fail("Maintenance is not configured for every day.")
    if len(maintenance.get("checks") or []) < 6:
        fail("The daily maintenance scope is incomplete.")
    if metrics.get("maintenance_frequency") != "daily" or "checked daily" not in str(metrics.get("publication_source_note") or "").lower():
        fail("Daily maintenance metadata is inconsistent.")
    if (ROOT / "site-status.json").exists() or "site-status.json" in sitemap:
        fail("The obsolete public status endpoint remains.")
    required_urls = [
        "https://ramtin-mojtahedi.github.io/",
        "https://ramtin-mojtahedi.github.io/about/",
        "https://ramtin-mojtahedi.github.io/research/",
        "https://ramtin-mojtahedi.github.io/publications/",
        "https://ramtin-mojtahedi.github.io/publications.json",
        "https://ramtin-mojtahedi.github.io/publications.bib",
        "https://ramtin-mojtahedi.github.io/publications.atom.xml",
        "https://ramtin-mojtahedi.github.io/scholarly-pages.json",
        *(
            f"https://ramtin-mojtahedi.github.io/publications/{publication['id']}/"
            for publication in publications
        ),
    ]
    sitemap_locations = re.findall(r"<loc>([^<]+)</loc>", sitemap)
    missing_urls = sorted(set(required_urls) - set(sitemap_locations))
    if missing_urls:
        fail(f"Sitemap entries are missing: {missing_urls}")
    unexpected_urls = sorted(set(sitemap_locations) - set(required_urls))
    if unexpected_urls:
        fail(f"Sitemap contains unexpected non-canonical URLs: {unexpected_urls}")
    if re.search(r"<lastmod>", sitemap, flags=re.IGNORECASE):
        fail("Sitemap last-modified values must be omitted until meaningful page-change dates are tracked.")

    robots = read(FILES["robots"])
    if not re.search(r"(?mi)^User-agent:\s*\*$", robots) or not re.search(r"(?mi)^Allow:\s*/$", robots):
        fail("robots.txt does not explicitly permit crawling.")
    if "Sitemap: https://ramtin-mojtahedi.github.io/sitemap.xml" not in robots:
        fail("robots.txt does not advertise the canonical sitemap.")

    key = read(FILES["indexnow_key"]).strip()
    manifest = read_json(FILES["indexnow"])
    if manifest.get("key") != key or manifest.get("keyLocation") != f"https://ramtin-mojtahedi.github.io/{key}.txt":
        fail("IndexNow key file and manifest differ.")
    if set(manifest.get("urlList") or []) != set(required_urls):
        fail("IndexNow URLs and canonical sitemap URLs differ.")


def main() -> int:
    structured_files = {
        "publications",
        "metrics",
        "maintenance",
        "publication_feed",
        "publication_bibtex",
        "publication_atom",
        "scholarly_pages",
    }
    sources = {name: read(path) for name, path in FILES.items() if name not in structured_files}
    parts = "\n".join(sources[name] for name in ("hero", "publications_section", "activity", "contact"))
    publications, metrics = validate_publications()
    counts = validate_counts(sources["hero"], sources["activity"], sources["contact"], metrics)
    validate_structure(sources["index"], parts)
    validate_public_copy(sources["index"], parts)
    validate_contact(sources["index"], sources["contact"], sources["contact_js"], sources["contact_css"])
    validate_scholarly_exports(publications)
    validate_discovery_pages(sources)
    validate_maintenance(publications, metrics)

    print("Website validation passed.")
    print(f"- Public sections: {len(REQUIRED_IDS) - 1}")
    print(f"- Publications: {len(publications)}")
    print(f"- Presentations: {counts['presentation_count']}")
    print(f"- Recognition entries: {counts['recognition_count']}")
    print(f"- Leadership roles: {counts['leadership_role_count']}")
    print("- Visitor-facing implementation markers: none")
    print("- Biography, research hub, Atom feed, and citation metadata: valid")
    print("- Maintenance schedule: daily")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (AssertionError, json.JSONDecodeError) as error:
        print(f"Website validation failed: {error}", file=sys.stderr)
        raise SystemExit(1)
