#!/usr/bin/env python3
"""Validate the portfolio's visual hierarchy, section clarity, and dynamic impact layer."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "index.html"
HERO = ROOT / "_includes" / "site-part-1.html"
PUBLICATIONS = ROOT / "_includes" / "site-part-2.html"
ACTIVITY = ROOT / "_includes" / "site-part-3.html"
SERVICE = ROOT / "_includes" / "site-part-4.html"
IMPACT_SCRIPT = ROOT / "assets" / "site-impact.js"
IMPACT_STYLE = ROOT / "assets" / "site-impact.css"
PROGRAMMING_SCRIPT = ROOT / "assets" / "programming-languages.js"

REQUIRED_SECTION_IDS = (
    "expertise",
    "profile",
    "experience",
    "publications",
    "presentations",
    "recognition",
    "teaching",
    "service",
    "code",
    "contact",
)

REQUIRED_STAT_LABELS = (
    "Research output",
    "Conference activity",
    "Recognition",
    "Professional service",
    "Teaching reach",
    "Leadership",
    "Technical breadth",
)

REMOVED_CONTACT_MARKERS = (
    'class="contact-assurance"',
    "Submitted from this page",
    "Reply-ready",
    "Uses the email you provide",
    "Spam and abuse safeguards",
)

FORBIDDEN_AUTHORSHIP_MARKERS = (
    "ai-generated",
    "generated by ai",
    "created by ai",
    "written by ai",
    "designed by ai",
    "built with ai",
    "made with ai",
    "ai-assisted website",
    "ai powered website",
    "ai-powered website",
    "chatgpt-generated",
    "powered by chatgpt",
)


def read(path: Path) -> str:
    if not path.is_file():
        raise AssertionError(f"Required file is missing: {path.relative_to(ROOT)}")
    return path.read_text(encoding="utf-8")


def require(source: str, tokens: tuple[str, ...], location: str) -> None:
    missing = [token for token in tokens if token not in source]
    if missing:
        raise AssertionError(f"Required impact text is missing from {location}: {missing}")


def main() -> int:
    index = read(INDEX)
    hero = read(HERO)
    publications = read(PUBLICATIONS)
    activity = read(ACTIVITY)
    service = read(SERVICE)
    impact_script = read(IMPACT_SCRIPT)
    impact_style = read(IMPACT_STYLE)
    programming_script = read(PROGRAMMING_SCRIPT)

    require(
        index,
        (
            'href="assets/site-impact.css?v=20260728-1"',
            'src="assets/site-impact.js?v=20260728-1"',
        ),
        "index.html",
    )
    if index.index("assets/programming-languages.js") > index.index("assets/site-impact.js"):
        raise AssertionError("Programming-language statistic must load before site-impact.js.")
    if index.index("assets/site-impact.js") > index.index("assets/site-2026.js"):
        raise AssertionError("site-impact.js must load before the core reveal and counter script.")

    require(
        impact_script,
        (
            "Research, leadership, and technical impact at a glance.",
            "Clinical relevance",
            "Technical rigour",
            "Reproducible delivery",
            "section-heading-enhanced",
            "section-status",
            "impact-stat",
            "scrollIntoView",
            "prefers-reduced-motion: reduce",
        ),
        "assets/site-impact.js",
    )
    for section_id in REQUIRED_SECTION_IDS:
        if f"id: '{section_id}'" not in impact_script:
            raise AssertionError(f"Section hierarchy configuration is missing: {section_id}")
    for label in REQUIRED_STAT_LABELS:
        if f"label: '{label}'" not in impact_script:
            raise AssertionError(f"Statistic clarity label is missing: {label}")

    if impact_script.count("target:") != len(REQUIRED_STAT_LABELS):
        raise AssertionError("The interactive statistic target count is inconsistent.")
    if programming_script.count("'Python'") != 1 or "'Bash'" not in programming_script:
        raise AssertionError("The programming-language statistic source is incomplete.")

    require(
        impact_style,
        (
            ".impact-intro",
            ".impact-stat",
            ".stat-kicker",
            ".section-heading-enhanced",
            ".section-index",
            ".section-status",
            ".section-current",
            "@media (prefers-reduced-motion: reduce)",
        ),
        "assets/site-impact.css",
    )
    if len(impact_style.splitlines()) < 250:
        raise AssertionError("The professional impact stylesheet appears incomplete.")

    require(
        publications,
        (
            "Research output",
            "Peer-reviewed publications and scholarly work.",
        ),
        "the publications section",
    )
    require(
        activity,
        (
            "Conference contributions",
            "Honours &amp; recognition",
            "Teaching impact",
            "Research communicated across medical imaging",
            "Competitive recognition for research achievement",
            "Instruction, mentorship, and academic support",
        ),
        "the presentations, recognition, and teaching sections",
    )
    require(
        service,
        (
            "Leadership &amp; service",
            "Leadership, mentorship, and professional service.",
            "Reproducible research repositories and implementations.",
            "Collaboration and professional inquiries.",
        ),
        "the service, open-source, and contact sections",
    )

    static_stats = len(re.findall(r"<div class='stat'>", hero))
    if static_stats != 6:
        raise AssertionError(f"Expected six source statistics before the dynamic language stat; found {static_stats}.")

    public_source = "\n".join((index, hero, publications, activity, service)).casefold()
    removed = [marker for marker in REMOVED_CONTACT_MARKERS if marker.casefold() in public_source]
    if removed:
        raise AssertionError(f"Removed contact markers remain visible: {removed}")
    forbidden = [marker for marker in FORBIDDEN_AUTHORSHIP_MARKERS if marker in public_source]
    if forbidden:
        raise AssertionError(f"Website-authorship markers remain visible: {forbidden}")

    print("Site-impact validation passed.")
    print(f"- Clear numbered sections: {len(REQUIRED_SECTION_IDS)}")
    print(f"- Interactive statistics: {len(REQUIRED_STAT_LABELS)}")
    print("- Professional snapshot: present")
    print("- Responsive and reduced-motion treatments: present")
    print("- Removed contact markers: absent")
    print("- Website-authorship markers: absent")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (AssertionError, OSError) as error:
        print(f"Site-impact validation failed: {error}", file=sys.stderr)
        raise SystemExit(1)
